// Generated by scripts/generate-design-rule-coverage-module.mjs. Do not edit by hand.
//
// A typed copy of issue 649/#650's audit/design-rule-coverage.json -- the real,
// measured rendered color-proportion percentages per preset, for GdsDesignRuleProfilePanel
// (issue 651) to import directly with zero runtime fetch cost. Regenerate with
// `npm run generate:design-rule-coverage-module`; `--check` fails on drift.
//
// A preset absent here has not yet been swept by issue 649's audit; consumers must
// handle that as a real "no data yet" case, never assume every GdsThemePresetId is present.

import type { GdsThemePresetId } from '@sovereignsquad/gds-theme';

/** One preset's measured rendered color-proportion percentages (issue 649/#650). */
export interface GdsDesignRuleCoverageEntry {
  dominant: number;
  secondary: number;
  accent: number;
  unclassified: number;
}

export const designRuleCoverageByPreset: Partial<Record<GdsThemePresetId, GdsDesignRuleCoverageEntry>> = {
  'amber': { dominant: 47.3, secondary: 0, accent: 0, unclassified: 52.7 },
  'athlete-gold': { dominant: 26.6, secondary: 0, accent: 0, unclassified: 73.4 },
  'aurora': { dominant: 47.8, secondary: 0, accent: 0, unclassified: 52.2 },
  'brand': { dominant: 48.4, secondary: 0, accent: 0, unclassified: 51.6 },
  'class-usa': { dominant: 48.2, secondary: 0, accent: 0, unclassified: 51.8 },
  'colorblind-safe': { dominant: 48, secondary: 0, accent: 0, unclassified: 52 },
  'coral': { dominant: 47.9, secondary: 0, accent: 0, unclassified: 52.1 },
  'cosmic': { dominant: 37.2, secondary: 0, accent: 0, unclassified: 62.8 },
  'dark-public': { dominant: 31.6, secondary: 0, accent: 0, unclassified: 68.4 },
  'default': { dominant: 47.5, secondary: 0, accent: 0, unclassified: 52.5 },
  'editorial': { dominant: 48.4, secondary: 0, accent: 0, unclassified: 51.6 },
  'flat-surface': { dominant: 48.4, secondary: 0, accent: 0, unclassified: 51.6 },
  'forest': { dominant: 48.3, secondary: 0, accent: 0, unclassified: 51.7 },
  'gold-athlete': { dominant: 48, secondary: 0, accent: 0, unclassified: 52 },
  'high-contrast': { dominant: 81.3, secondary: 0, accent: 0, unclassified: 18.7 },
  'mint': { dominant: 47.9, secondary: 0, accent: 0, unclassified: 52.1 },
  'neon-night': { dominant: 46.9, secondary: 0, accent: 0, unclassified: 53.1 },
  'oceanic': { dominant: 46.9, secondary: 0, accent: 0, unclassified: 53.1 },
  'orchid': { dominant: 47.6, secondary: 0, accent: 0, unclassified: 52.4 },
  'partner-discovery': { dominant: 48.4, secondary: 0, accent: 0, unclassified: 51.6 },
  'royal': { dominant: 47.1, secondary: 0, accent: 0, unclassified: 52.9 },
  'ruby': { dominant: 48.6, secondary: 0, accent: 0, unclassified: 51.4 },
  'skyline': { dominant: 47.8, secondary: 0, accent: 0, unclassified: 52.2 },
  'sunset': { dominant: 48, secondary: 0, accent: 0, unclassified: 52 },
  'warm': { dominant: 26.4, secondary: 0, accent: 0, unclassified: 73.6 },
};
