const referenceThemeExplorerCopy = {
  en: {
    themeLabTitle: 'Theme Lab',
    themeLabDescription: 'Test the actual shipped GDS theme presets, color-scheme behavior, and the governed brand-theme generator. This page is part of the live proof, not a separate styling experiment.',
    themePresetTitle: 'Theme preset',
    presetLabel: 'Preset',
    previewColorSchemeLabel: 'Preview color scheme',
    webfontLaneLabel: 'Webfont lane',
    resetThemeLab: 'Reset theme lab',
    shellBehavior: 'Theme changes apply to the official site shell so visitors can validate real whole-page runtime behavior.',
    brandOptionsTitle: 'Brand builder options',
    brandPrimaryColorLabel: 'Brand primary color',
    useFlatSurfaces: 'Use flat surfaces',
    useEditorialSerif: 'Use editorial serif headings',
    generatorDescription: 'The generator composes shipped helpers instead of creating a second theme authority inside the website.',
    currentSelectionTitle: 'Current selection summary',
    bestFor: 'Best for:',
    runtimeLane: 'Runtime lane:',
    colorScheme: 'Color scheme:',
    darkForwardNotice: 'This vibrant preset renders in the selected color scheme inside the live preview.',
    compareToggle: 'Compare against a second shipped preset',
    comparisonPresetLabel: 'Comparison preset',
    shippedLanesTitle: 'Shipped theme lanes',
    shippedLanesDescription: 'Every lane below is a supported runtime preset. Colourful lanes ship as full CSS-based VibeThemes: canvas, shell, surface, control, focus, and accent tokens, not bitmap backgrounds.',
    selected: 'Selected',
    cssVibeTheme: 'CSS VibeTheme',
    previewVibe: 'Preview this vibe',
    avoidFor: 'Avoid for:',
    noSpecialExclusion: 'No special exclusion noted for this lane.',
    athleteGoldReferenceTitle: 'Athlete Gold reference surface',
    athleteGoldReferenceDescription: 'Black performance navigation with stronger metallic gold, based on the shipped Athlete Gold VibeTheme tokens.',
    vibeContractTitle: 'Current VibeTheme contract',
    vibeContractDescription: 'The selected preset exports these package-owned CSS tokens. Consumers can render expressive product surfaces while staying inside GDS theme ownership.',
    tokenLabels: ['Primary', 'Accent', 'Light canvas', 'Dark canvas', 'Light surface', 'Dark surface'],
    proofTitle: 'Light, dark, and auto proof',
    proofDescription: 'Every official lane must remain usable across explicit light, explicit dark, and OS-controlled auto modes. The dark-public lane is intentionally forced to dark in preview to preserve its contrast contract.',
    requiredProof: 'Required proof: semantic text, visible focus, and contrast-safe state treatment.',
    livePreviewTitle: 'Live Theme Preview',
    livePreviewDescription: 'Visitors can test the shipped presets, compare lanes, and inspect actual GDS surfaces under each theme.',
    comparisonPreviewTitle: 'Comparison Preview Surface',
    comparisonPreviewDescription: 'Compare another shipped theme against the current selection before adopting it downstream.',
    unsupportedTitle: 'Unsupported lane boundary',
    unsupportedDescription: 'Unsupported local theme lanes are blocked by policy and compliance because they create parallel design-system authority.',
    doNotCreateTitle: 'Do not create local branding-layer helpers',
    doNotCreateDescription: 'If a consumer needs brand expression, use createPublicBrandTheme(...). If a lane is missing, request it for GDS instead of building extendGdsTheme(...), createTheme(...), or mergeMantineTheme(...) ownership locally.',
    approvedRemediation: 'Approved remediation',
    prohibitedOwnership: 'Prohibited ownership',
    accentContrastTitle: 'Accent contrast',
    accentContrastDescription: 'Every accent, shade and mode measured against its threshold for the selected preset and scheme.',
    previewBestFor: 'Best for:',
    previewColorScheme: 'Color scheme:',
    previewA11yProof: 'Accessibility proof:',
    previewA11yDescription: 'status uses text, badge label, and placement, not color alone.',
    forcedDarkPreview: 'This lane previews in the selected color scheme so the runtime stays inside its sanctioned contrast contract.',
    tokenControls: 'Token-backed controls',
    referenceInput: 'Reference input',
    referenceInputDescription: 'Inputs stay inside the theme lane instead of drifting into route-local styling.',
    referenceInputPlaceholder: 'Search or type a route name',
    success: 'Success',
    warning: 'Warning',
    critical: 'Critical',
    proofSurfaceTitle: 'Reference site proof surface',
    proofSurfaceDescription: 'This preview uses the real shipped design-system runtime rather than a docs-only styling lane.',
    inspectRoute: 'Inspect route',
    metadataRuntimeLane: 'Runtime lane',
    metadataColorScheme: 'Color scheme',
    metadataA11yProof: 'A11y proof',
    metadataA11yValue: 'Keyboard + readable states',
    appsAlignedWith: 'Apps aligned with',
    generalAdoptionWith: 'General product adoption with',
    avoidLocalTheme: 'Avoid creating a local non-canonical theme authority.',
    schemes: { light: 'Light', dark: 'Dark', auto: 'Auto' },
    schemeDescriptions: {
      light: 'Validates readable default surfaces, controls, badges, and focus states against light backgrounds.',
      dark: 'Validates contrast for public, operational, and feedback surfaces when dark mode is active.',
      auto: 'Documents the adopter path for OS-controlled schemes while keeping the provider contract unchanged.',
    },
    presetLabels: {
      default: 'Default runtime theme',
      'dark-public': 'Dark public theme',
      'flat-surface': 'Flat surface theme',
      editorial: 'Editorial serif theme',
      brand: 'Brand theme generator',
      sunset: 'Sunset pulse',
      oceanic: 'Oceanic wave',
      forest: 'Forest signal',
      ruby: 'Ruby spark',
      amber: 'Amber glow',
      'neon-night': 'Neon night',
      skyline: 'Skyline indigo',
      aurora: 'Aurora teal',
      coral: 'Coral bloom',
      mint: 'Mint circuit',
      orchid: 'Orchid signal',
      royal: 'Royal violet',
      cosmic: 'Cosmic burst',
      'athlete-gold': 'Athlete Gold',
    },
    presetSummaries: {
      default: 'Balanced neutral baseline lane.',
      'dark-public': 'Dark-first public presentation lane.',
      'flat-surface': 'Lower-elevation operational lane.',
      editorial: 'Reading-focused lane with serif headlines.',
      brand: 'Governed brand composition lane.',
      sunset: 'Warm orange-magenta vibrant lane.',
      oceanic: 'Cool cyan-blue vibrant lane.',
      forest: 'Natural emerald-led vibrant lane.',
      ruby: 'Strong red high-contrast lane.',
      amber: 'Golden energetic lane.',
      'neon-night': 'Lime-accented vibrant lane.',
      skyline: 'Indigo technology-forward lane.',
      aurora: 'Fresh teal-cyan app lane for optimistic product surfaces.',
      coral: 'Expressive pink-coral lane for creator, commerce, and social products.',
      mint: 'Clean green-mint lane for health, learning, and growth products.',
      orchid: 'Purple-grape lane for editorial, culture, and premium tools.',
      royal: 'Confident violet lane for SaaS dashboards and professional apps.',
      cosmic: 'Highly saturated blue-violet-cyan-magenta showcase lane for bold public apps and launch surfaces.',
      'athlete-gold': 'Premium black-and-gold performance lane with metallic gold accents.',
    },
  },
  de: {
    themeLabTitle: 'Theme-Labor',
    themeLabDescription: 'Teste die ausgelieferten GDS-Theme-Presets, das Farbschema-Verhalten und den gesteuerten Brand-Theme-Generator. Diese Seite ist Teil der Live-Demo, kein separates Styling-Experiment.',
    themePresetTitle: 'Theme-Preset',
    presetLabel: 'Preset',
    previewColorSchemeLabel: 'Vorschau-Farbschema',
    webfontLaneLabel: 'Webfont-Lane',
    resetThemeLab: 'Theme-Labor zurücksetzen',
    shellBehavior: 'Theme-Änderungen wirken auf die offizielle Site-Shell, damit Besucher echtes Ganzseitenverhalten prüfen können.',
    brandOptionsTitle: 'Optionen des Brand-Builders',
    brandPrimaryColorLabel: 'Primäre Markenfarbe',
    useFlatSurfaces: 'Flache Oberflächen verwenden',
    useEditorialSerif: 'Editoriale Serif-Überschriften verwenden',
    generatorDescription: 'Der Generator kombiniert ausgelieferte Helfer, statt im Website-Code eine zweite Theme-Autorität aufzubauen.',
    currentSelectionTitle: 'Zusammenfassung der Auswahl',
    bestFor: 'Geeignet für:',
    runtimeLane: 'Runtime-Lane:',
    colorScheme: 'Farbschema:',
    darkForwardNotice: 'Dieses Vibrant-Preset rendert in der Live-Vorschau im ausgewählten Farbschema.',
    compareToggle: 'Mit einem zweiten ausgelieferten Preset vergleichen',
    comparisonPresetLabel: 'Vergleichs-Preset',
    shippedLanesTitle: 'Ausgelieferte Theme-Lanes',
    shippedLanesDescription: 'Jede Lane unten ist ein unterstütztes Runtime-Preset. Farbige Lanes werden als vollständige CSS-basierte VibeThemes ausgeliefert: Canvas, Shell, Surface, Controls, Focus und Accent-Tokens, keine Bitmap-Hintergründe.',
    selected: 'Ausgewählt',
    cssVibeTheme: 'CSS VibeTheme',
    previewVibe: 'Diesen Vibe ansehen',
    avoidFor: 'Vermeiden für:',
    noSpecialExclusion: 'Für diese Lane ist kein besonderer Ausschluss vermerkt.',
    vibeContractTitle: 'Aktueller VibeTheme-Vertrag',
    vibeContractDescription: 'Das ausgewählte Preset exportiert diese package-eigenen CSS-Tokens. Consumer können expressive Produktflächen rendern und bleiben in der GDS-Theme-Ownership.',
    tokenLabels: ['Primär', 'Akzent', 'Heller Canvas', 'Dunkler Canvas', 'Helle Oberfläche', 'Dunkle Oberfläche'],
    proofTitle: 'Proof für Hell, Dunkel und Auto',
    proofDescription: 'Jede offizielle Lane muss in explizitem Hellmodus, explizitem Dunkelmodus und OS-gesteuertem Auto-Modus nutzbar bleiben. Die Dark-Public-Lane wird in der Vorschau bewusst dunkel erzwungen.',
    requiredProof: 'Erforderlicher Proof: semantischer Text, sichtbarer Fokus und kontrastsichere Statusbehandlung.',
    livePreviewTitle: 'Live-Theme-Vorschau',
    livePreviewDescription: 'Besucher können ausgelieferte Presets testen, Lanes vergleichen und echte GDS-Flächen unter jedem Theme prüfen.',
    comparisonPreviewTitle: 'Vergleichs-Vorschaufläche',
    comparisonPreviewDescription: 'Vergleiche ein weiteres ausgeliefertes Theme mit der aktuellen Auswahl, bevor es downstream übernommen wird.',
    unsupportedTitle: 'Grenze nicht unterstützter Lanes',
    unsupportedDescription: 'Nicht unterstützte lokale Theme-Lanes werden durch Policy und Compliance blockiert, weil sie parallele Design-System-Autorität schaffen.',
    doNotCreateTitle: 'Keine lokalen Branding-Layer-Helfer erstellen',
    doNotCreateDescription: 'Wenn ein Consumer Markenausdruck braucht, verwende createPublicBrandTheme(...). Fehlt eine Lane, fordere sie für GDS an, statt lokal extendGdsTheme(...), createTheme(...) oder mergeMantineTheme(...) aufzubauen.',
    approvedRemediation: 'Genehmigte Abhilfe',
    prohibitedOwnership: 'Verbotene Ownership',
    accentContrastTitle: 'Akzentkontrast',
    accentContrastDescription: 'Jeder Akzent, jede Abstufung und jeder Modus wird für das gewählte Preset und Schema an seinem Schwellenwert gemessen.',
    previewBestFor: 'Geeignet für:',
    previewColorScheme: 'Farbschema:',
    previewA11yProof: 'Accessibility-Proof:',
    previewA11yDescription: 'Status nutzt Text, Badge-Label und Platzierung, nicht nur Farbe.',
    forcedDarkPreview: 'Diese Lane wird immer dunkel dargestellt, damit die Runtime im genehmigten Kontrastvertrag bleibt.',
    tokenControls: 'Token-gestützte Controls',
    referenceInput: 'Referenzeingabe',
    referenceInputDescription: 'Eingaben bleiben in der Theme-Lane, statt in routenlokales Styling abzudriften.',
    referenceInputPlaceholder: 'Route suchen oder Namen eingeben',
    success: 'Erfolg',
    warning: 'Warnung',
    critical: 'Kritisch',
    proofSurfaceTitle: 'Proof-Fläche der Referenzseite',
    proofSurfaceDescription: 'Diese Vorschau nutzt die echte ausgelieferte Design-System-Runtime statt einer docs-only Styling-Lane.',
    inspectRoute: 'Route prüfen',
    metadataRuntimeLane: 'Runtime-Lane',
    metadataColorScheme: 'Farbschema',
    metadataA11yProof: 'A11y-Proof',
    metadataA11yValue: 'Tastatur + lesbare Zustände',
    appsAlignedWith: 'Apps ausgerichtet auf',
    generalAdoptionWith: 'Allgemeine Produktadoption mit',
    avoidLocalTheme: 'Keine lokale nicht-kanonische Theme-Autorität erstellen.',
    schemes: { light: 'Hell', dark: 'Dunkel', auto: 'Auto' },
    schemeDescriptions: {
      light: 'Prüft lesbare Standardflächen, Controls, Badges und Fokuszustände auf hellen Hintergründen.',
      dark: 'Prüft Kontrast für Public-, Operations- und Feedback-Flächen im Dunkelmodus.',
      auto: 'Dokumentiert den Adopter-Pfad für OS-gesteuerte Schemes bei unverändertem Provider-Vertrag.',
    },
    presetLabels: {
      default: 'Standard-Runtime-Theme',
      'dark-public': 'Dunkles Public-Theme',
      'flat-surface': 'Flat-Surface-Theme',
      editorial: 'Editoriales Serif-Theme',
      brand: 'Brand-Theme-Generator',
      sunset: 'Sunset Pulse',
      oceanic: 'Oceanic Wave',
      forest: 'Forest Signal',
      ruby: 'Ruby Spark',
      amber: 'Amber Glow',
      'neon-night': 'Neon Night',
      skyline: 'Skyline Indigo',
      aurora: 'Aurora Teal',
      coral: 'Coral Bloom',
      mint: 'Mint Circuit',
      orchid: 'Orchid Signal',
      royal: 'Royal Violet',
      cosmic: 'Cosmic Burst',
    },
    presetSummaries: {
      default: 'Ausgewogene, neutrale Basis-Lane.',
      'dark-public': 'Dunkel-first Public-Lane.',
      'flat-surface': 'Operative Lane mit geringerer Elevation.',
      editorial: 'Lesefokussierte Lane mit Serif-Headlines.',
      brand: 'Gesteuerte Brand-Composition-Lane.',
      sunset: 'Warme orange-magenta Vibrant-Lane.',
      oceanic: 'Kühle cyan-blaue Vibrant-Lane.',
      forest: 'Natürliche smaragdgetriebene Vibrant-Lane.',
      ruby: 'Kräftige rote High-Contrast-Lane.',
      amber: 'Goldgelbe energetische Lane.',
      'neon-night': 'Lime-akzentuierte Vibrant-Lane.',
      skyline: 'Indigo Technology-Forward-Lane.',
      aurora: 'Frische teal-cyan App-Lane für optimistische Produktflächen.',
      coral: 'Expressive pink-coral Lane für Creator-, Commerce- und Social-Produkte.',
      mint: 'Saubere grün-mint Lane für Health, Learning und Growth.',
      orchid: 'Purple-grape Lane für Editorial, Kultur und Premium-Tools.',
      royal: 'Selbstbewusste violette Lane für SaaS-Dashboards und professionelle Apps.',
      cosmic: 'Hochgesättigte blue-violet-cyan-magenta Showcase-Lane für mutige Public Apps und Launch-Flächen.',
    },
  },
  hu: {
    themeLabTitle: 'Témalabor',
    themeLabDescription: 'Teszteld a szállított GDS téma preseteket, a színséma működését és a szabályozott brand-theme generátort. Ez az oldal a live demó része, nem külön styling-kísérlet.',
    themePresetTitle: 'Téma preset',
    presetLabel: 'Téma preset',
    previewColorSchemeLabel: 'Előnézeti színséma',
    webfontLaneLabel: 'Webfont sáv',
    resetThemeLab: 'Témalabor visszaállítása',
    shellBehavior: 'A témaváltások az official site shellre is érvényesek, így a látogatók valódi teljes oldalas runtime viselkedést ellenőrizhetnek.',
    brandOptionsTitle: 'Brand builder opciók',
    brandPrimaryColorLabel: 'Elsődleges brand szín',
    useFlatSurfaces: 'Lapos felületek használata',
    useEditorialSerif: 'Editorial serif címsorok használata',
    generatorDescription: 'A generátor szállított helpereket komponál, nem hoz létre második téma-autoritást a website-ban.',
    currentSelectionTitle: 'Aktuális választás összefoglalója',
    bestFor: 'Legjobb erre:',
    runtimeLane: 'Runtime lane:',
    colorScheme: 'Színséma:',
    darkForwardNotice: 'Ez a vibrant preset a live előnézetben a kiválasztott színsémában jelenik meg.',
    compareToggle: 'Összehasonlítás második szállított presettel',
    comparisonPresetLabel: 'Összehasonlító preset',
    shippedLanesTitle: 'Szállított téma lane-ek',
    shippedLanesDescription: 'Minden lenti lane támogatott runtime preset. A színes lane-ek teljes CSS-alapú VibeTheme-ként érkeznek: canvas, shell, surface, control, focus és accent tokenekkel, nem bitmap hátterekkel.',
    selected: 'Kiválasztva',
    cssVibeTheme: 'CSS VibeTheme',
    previewVibe: 'Vibe előnézete',
    avoidFor: 'Kerüld erre:',
    noSpecialExclusion: 'Ehhez a lane-hez nincs külön kizárás megadva.',
    vibeContractTitle: 'Aktuális VibeTheme szerződés',
    vibeContractDescription: 'A kiválasztott preset ezeket a package-owned CSS tokeneket exportálja. A consumerek kifejező product surface-eket renderelhetnek GDS theme ownership-en belül.',
    tokenLabels: ['Elsődleges', 'Akcentus', 'Világos canvas', 'Sötét canvas', 'Világos felület', 'Sötét felület'],
    proofTitle: 'Light, dark és auto proof',
    proofDescription: 'Minden official lane-nek használhatónak kell maradnia explicit light, explicit dark és OS-controlled auto módban. A dark-public lane előnézetben szándékosan dark módra van kényszerítve.',
    requiredProof: 'Kötelező proof: szemantikus szöveg, látható fókusz és kontrasztbiztos állapotkezelés.',
    livePreviewTitle: 'Live téma előnézet',
    livePreviewDescription: 'A látogatók tesztelhetik a szállított preseteket, összehasonlíthatják a lane-eket és ellenőrizhetik a valódi GDS felületeket minden témában.',
    comparisonPreviewTitle: 'Összehasonlító előnézeti felület',
    comparisonPreviewDescription: 'Hasonlíts össze egy másik szállított témát az aktuális választással, mielőtt downstream adoptálod.',
    unsupportedTitle: 'Nem támogatott lane határa',
    unsupportedDescription: 'A nem támogatott lokális téma lane-eket policy és compliance blokkolja, mert párhuzamos design-system autoritást hoznak létre.',
    doNotCreateTitle: 'Ne hozz létre lokális branding-layer helpereket',
    doNotCreateDescription: 'Ha egy consumer brand kifejezést igényel, használd a createPublicBrandTheme(...)-et. Ha hiányzik egy lane, GDS-ben kérd, ne lokálisan építs extendGdsTheme(...), createTheme(...) vagy mergeMantineTheme(...) ownership-et.',
    approvedRemediation: 'Jóváhagyott javítás',
    prohibitedOwnership: 'Tiltott ownership',
    accentContrastTitle: 'Akcentkontraszt',
    accentContrastDescription: 'Minden akcent, árnyalat és mód a kiválasztott előbeállításhoz és sémához mérve a küszöbértékéhez képest.',
    previewBestFor: 'Legjobb erre:',
    previewColorScheme: 'Színséma:',
    previewA11yProof: 'Accessibility proof:',
    previewA11yDescription: 'az állapot szöveget, badge labelt és elhelyezést használ, nem csak színt.',
    forcedDarkPreview: 'Ez a lane a kiválasztott színsémában látszik, hogy a runtime a jóváhagyott kontraszt contracton belül maradjon.',
    tokenControls: 'Token-backed controlok',
    referenceInput: 'Referencia input',
    referenceInputDescription: 'Az inputok a téma lane-en belül maradnak, nem csúsznak route-local stylingba.',
    referenceInputPlaceholder: 'Keress vagy írj be route nevet',
    success: 'Siker',
    warning: 'Figyelmeztetés',
    critical: 'Kritikus',
    proofSurfaceTitle: 'Reference site proof surface',
    proofSurfaceDescription: 'Ez az előnézet a valódi szállított design-system runtime-ot használja, nem docs-only styling lane-t.',
    inspectRoute: 'Route vizsgálata',
    metadataRuntimeLane: 'Runtime lane',
    metadataColorScheme: 'Színséma',
    metadataA11yProof: 'A11y proof',
    metadataA11yValue: 'Billentyűzet + olvasható állapotok',
    appsAlignedWith: 'Alkalmazások ehhez igazítva:',
    generalAdoptionWith: 'Általános product adoption ezzel:',
    avoidLocalTheme: 'Ne hozz létre lokális, nem kanonikus téma-autoritást.',
    schemes: { light: 'Világos', dark: 'Sötét', auto: 'Auto' },
    schemeDescriptions: {
      light: 'Ellenőrzi az olvasható alapfelületeket, controlokat, badge-eket és fókuszállapotokat világos háttéren.',
      dark: 'Ellenőrzi a public, operational és feedback felületek kontrasztját aktív dark módban.',
      auto: 'Dokumentálja az OS-controlled scheme adopter útját változatlan provider contract mellett.',
    },
    presetLabels: {
      default: 'Alap runtime téma',
      'dark-public': 'Sötét public téma',
      'flat-surface': 'Lapos felület téma',
      editorial: 'Editorial serif téma',
      brand: 'Brand téma generátor',
      sunset: 'Sunset pulse',
      oceanic: 'Oceanic wave',
      forest: 'Forest signal',
      ruby: 'Ruby spark',
      amber: 'Amber glow',
      'neon-night': 'Neon night',
      skyline: 'Skyline indigo',
      aurora: 'Aurora teal',
      coral: 'Coral bloom',
      mint: 'Mint circuit',
      orchid: 'Orchid signal',
      royal: 'Royal violet',
      cosmic: 'Cosmic burst',
    },
    presetSummaries: {
      default: 'Kiegyensúlyozott, neutrális baseline lane.',
      'dark-public': 'Dark-first public lane.',
      'flat-surface': 'Alacsonyabb elevation operációs lane.',
      editorial: 'Olvasásközpontú lane serif headline-okkal.',
      brand: 'Szabályozott brand composition lane.',
      sunset: 'Meleg narancs-magenta vibrant lane.',
      oceanic: 'Hűvös cyan-kék vibrant lane.',
      forest: 'Természetes emerald-központú vibrant lane.',
      ruby: 'Erős piros, magas kontrasztú lane.',
      amber: 'Aranysárga, energikus lane.',
      'neon-night': 'Lime-akcentusú vibrant lane.',
      skyline: 'Indigo, technology-forward lane.',
      aurora: 'Friss teal-cyan app lane optimista product surface-ekhez.',
      coral: 'Kifejező pink-coral lane creator, commerce és social productokhoz.',
      mint: 'Tiszta zöld-mint lane health, learning és growth productokhoz.',
      orchid: 'Purple-grape lane editorial, culture és premium toolokhoz.',
      royal: 'Magabiztos violet lane SaaS dashboardokhoz és professzionális appokhoz.',
      cosmic: 'Erősen telített blue-violet-cyan-magenta showcase lane merész public appokhoz és launch surface-ekhez.',
    },
  },
    zh: {
    themeLabTitle: '主题实验室',
    themeLabDescription: '测试实际发布的 GDS 主题预设、配色方案行为和受管理的品牌主题生成器。此页面是现场校样的一部分，而不是单独的样式实验。',
    themePresetTitle: '主题预设',
    presetLabel: '预设',
    previewColorSchemeLabel: '预览配色方案',
    webfontLaneLabel: '网页字体通道',
    resetThemeLab: '重置主题实验室',
    shellBehavior: '主题更改适用于官方站点外壳，以便访问者可以验证真正的全页面运行时行为。',
    brandOptionsTitle: '品牌建设者选项',
    brandPrimaryColorLabel: '品牌原色',
    useFlatSurfaces: '使用平坦的表面',
    useEditorialSerif: '使用社论衬线标题',
    generatorDescription: '生成器组成已发送的帮助程序，而不是在网站内创建第二个主题权限。',
    currentSelectionTitle: '当前选型总结',
    bestFor: '最适合：',
    runtimeLane: '运行时车道：',
    colorScheme: '配色方案：',
    darkForwardNotice: '这个充满活力的预设在实时预览中以选定的配色方案进行渲染。',
    compareToggle: '与第二个出厂预设进行比较',
    comparisonPresetLabel: '比较预设',
    shippedLanesTitle: '已发货主题车道',
    shippedLanesDescription: '下面的每个通道都是受支持的运行时预设。彩色通道作为完整的基于 CSS 的 VibeThemes 提供：画布、外壳、表面、控制、焦点和重音标记，而不是位图背景。',
    selected: '已选择',
    cssVibeTheme: 'CSS Vibe主题',
    previewVibe: '预览一下这个氛围',
    avoidFor: '避免：',
    noSpecialExclusion: '这条车道没有特别排除。',
    athleteGoldReferenceTitle: '运动员金参考面',
    athleteGoldReferenceDescription: '黑色性能导航搭配更强的金属金色，基于已发货的 Athlete Gold VibeTheme 代币。',
    vibeContractTitle: '当前 VibeTheme 合同',
    vibeContractDescription: '选定的预设会导出这些包拥有的 CSS 令牌。消费者可以在保持 GDS 主题所有权的同时呈现富有表现力的产品表面。',
    tokenLabels: ['基本的', '口音', '浅色帆布', '深色画布', '光面', '深色表面'],
    proofTitle: '亮、暗和自动校样',
    proofDescription: '每个官方车道必须在显式亮光、显式暗光和操作系统控制的自动模式下保持可用。黑暗的公共车道在预览中被故意强制变暗，以保持其对比度契约。',
    requiredProof: '所需证明：语义文本、可见焦点和对比安全状态处理。',
    livePreviewTitle: '实时主题预览',
    livePreviewDescription: '访客可以测试已提供的预设、比较车道并检查每个主题下的实际 GDS 表面。',
    comparisonPreviewTitle: '比较预览表面',
    comparisonPreviewDescription: '在下游采用之前，将另一个已发布的主题与当前选择进行比较。',
    unsupportedTitle: '不受支持的车道边界',
    unsupportedDescription: '不受支持的本地主题通道会受到政策和合规性的阻碍，因为它们创建了并行设计系统权限。',
    doNotCreateTitle: '不要创建本地品牌层助手',
    doNotCreateDescription: '如果消费者需要品牌表达，请使用createPublicBrandTheme(...)。如果缺少通道，请向 GDS 请求该通道，而不是在本地构建extendGdsTheme(...)、createTheme(...) 或mergeMantineTheme(...) 所有权。',
    approvedRemediation: '批准的补救措施',
    prohibitedOwnership: '禁止拥有',
    accentContrastTitle: '强调对比',
    accentContrastDescription: '每个口音、色调和模式都根据所选预设和方案的阈值进行测量。',
    previewBestFor: '最适合：',
    previewColorScheme: '配色方案：',
    previewA11yProof: '可访问性证明：',
    previewA11yDescription: '状态使用文本、徽章标签和位置，而不仅仅是颜色。',
    forcedDarkPreview: '该通道以选定的配色方案进行预览，因此运行时间保持在其认可的对比度合同范围内。',
    tokenControls: '令牌支持的控件',
    referenceInput: '参考输入',
    referenceInputDescription: '输入保留在主题通道内，而不是漂移到路线本地样式中。',
    referenceInputPlaceholder: '搜索或输入路线名称',
    success: '成功',
    warning: '警告',
    critical: '批判的',
    proofSurfaceTitle: '参考场地证明面',
    proofSurfaceDescription: '此预览使用实际发布的设计系统运行时，而不是仅文档样式通道。',
    inspectRoute: '检查路线',
    metadataRuntimeLane: '运行时通道',
    metadataColorScheme: '配色方案',
    metadataA11yProof: 'A11y证明',
    metadataA11yValue: '键盘+可读状态',
    appsAlignedWith: '应用程序符合',
    generalAdoptionWith: '一般产品采用',
    avoidLocalTheme: '避免创建本地非规范主题权威。',
    schemes: { light: '光', dark: '黑暗的', auto: '汽车' },
    schemeDescriptions: {
      light: '在浅色背景下验证可读的默认表面、控件、徽章和焦点状态。',
      dark: '当暗模式处于活动状态时，验证公共、操作和反馈表面的对比度。',
      auto: '记录操作系统控制方案的采用者路径，同时保持提供商合同不变。',
    },
    presetLabels: {
      default: '默认运行时主题',
      '暗公开': '深色公共主题',
      '平面': '平面主题',
      editorial: '编辑衬线主题',
      brand: '品牌主题生成器',
      sunset: '日落脉冲',
      oceanic: '海洋波浪',
      forest: '森林信号',
      ruby: '红宝石火花',
      amber: '琥珀色光芒',
      '霓虹之夜': '霓虹之夜',
      skyline: '天际线靛蓝',
      aurora: '极光青色',
      coral: '珊瑚绽放',
      mint: '薄荷电路',
      orchid: '兰花信号',
      royal: '皇家紫罗兰',
      cosmic: '宇宙爆发',
      '运动员金牌': '运动员金奖',
    },
    presetSummaries: {
      default: '平衡的中立基线车道。',
      '暗公开': '黑暗优先的公共演示通道。',
      '平面': '低海拔作业车道。',
      editorial: '以阅读为中心的小巷，带有衬线标题。',
      brand: '受控品牌构成车道。',
      sunset: '温暖的橙洋红色充满活力的小巷。',
      oceanic: '凉爽的青蓝色充满活力的小巷。',
      forest: '以天然翡翠为主导的活力巷。',
      ruby: '强烈的红色高对比度车道。',
      amber: '金色活力巷。',
      '霓虹之夜': '青柠味的充满活力的小巷。',
      skyline: 'Indigo 技术前沿。',
      aurora: '清新的青色-青色应用通道，呈现乐观的产品表面。',
      coral: '富有表现力的粉红色珊瑚巷，适合创作者、商业和社交产品。',
      mint: '干净的绿薄荷巷，出售健康、学习和成长产品。',
      orchid: '用于编辑、文化和高级工具的紫葡萄巷。',
      royal: '适用于 SaaS 仪表板和专业应用程序的自信紫罗兰通道。',
      cosmic: '高度饱和的蓝-紫-青-洋红展示通道，用于大胆的公共应用程序和启动表面。',
      '运动员金牌': '高级黑金性能通道，带有金属金色装饰。',
    },
  },
    ko: {
    themeLabTitle: '테마 연구실',
    themeLabDescription: '실제 제공되는 GDS 테마 사전 설정, 색 구성표 동작 및 관리되는 브랜드 테마 생성기를 테스트합니다. 이 페이지는 별도의 스타일링 실험이 아닌 라이브 프루프의 일부입니다.',
    themePresetTitle: '테마 사전 설정',
    presetLabel: '프리셋',
    previewColorSchemeLabel: '색 구성표 미리보기',
    webfontLaneLabel: '웹폰트 레인',
    resetThemeLab: '테마 연구소 재설정',
    shellBehavior: '테마 변경 사항은 공식 사이트 셸에 적용되므로 방문자는 실제 전체 페이지 런타임 동작을 확인할 수 있습니다.',
    brandOptionsTitle: '브랜드 빌더 옵션',
    brandPrimaryColorLabel: '브랜드 기본 색상',
    useFlatSurfaces: '평평한 표면을 사용하세요',
    useEditorialSerif: '편집 세리프 제목을 사용하세요.',
    generatorDescription: '생성기는 웹 사이트 내에 두 번째 테마 권한을 생성하는 대신 제공된 도우미를 구성합니다.',
    currentSelectionTitle: '현재 선택 요약',
    bestFor: '가장 적합한 대상:',
    runtimeLane: '런타임 레인:',
    colorScheme: '색 구성표:',
    darkForwardNotice: '이 생생한 사전 설정은 실시간 미리 보기 내에서 선택한 색상 구성표로 렌더링됩니다.',
    compareToggle: '두 번째로 배송된 사전 설정과 비교',
    comparisonPresetLabel: '비교 프리셋',
    shippedLanesTitle: '배송된 테마 레인',
    shippedLanesDescription: '아래의 모든 레인은 지원되는 런타임 사전 설정입니다. 다채로운 레인은 비트맵 배경이 아닌 캔버스, 쉘, 표면, 컨트롤, 포커스 및 액센트 토큰과 같은 완전한 CSS 기반 VibeThemes로 제공됩니다.',
    selected: '선택된',
    cssVibeTheme: 'CSS 바이브 테마',
    previewVibe: '분위기 미리보기',
    avoidFor: '다음의 경우에는 피하세요:',
    noSpecialExclusion: '이 차선에는 특별한 제외 사항이 명시되어 있지 않습니다.',
    athleteGoldReferenceTitle: 'Athlete Gold 기준면',
    athleteGoldReferenceDescription: '배송된 Athlete Gold VibeTheme 토큰을 기반으로 더욱 강한 메탈릭 골드를 사용한 블랙 퍼포먼스 탐색.',
    vibeContractTitle: '현재 VibeTheme 계약',
    vibeContractDescription: '선택한 사전 설정은 이러한 패키지 소유 CSS 토큰을 내보냅니다. 소비자는 GDS 테마 소유권을 유지하면서 표현력 있는 제품 표면을 렌더링할 수 있습니다.',
    tokenLabels: ['주요한', '악센트', '가벼운 캔버스', '어두운 캔버스', '가벼운 표면', '어두운 표면'],
    proofTitle: '밝음, 어두움 및 자동 교정',
    proofDescription: '모든 공식 차선은 명시적 밝음, 명시적 어두움 및 OS 제어 자동 모드에서 계속 사용할 수 있어야 합니다. 어두운 공용 차선은 대비 계약을 유지하기 위해 미리보기에서 의도적으로 어두워지게 됩니다.',
    requiredProof: '필수 증명: 의미 체계 텍스트, 가시적 초점, 대비 안전 상태 처리.',
    livePreviewTitle: '라이브 테마 미리보기',
    livePreviewDescription: '방문자는 제공된 사전 설정을 테스트하고, 차선을 비교하고, 각 테마에서 실제 GDS 표면을 검사할 수 있습니다.',
    comparisonPreviewTitle: '비교 미리보기 표면',
    comparisonPreviewDescription: '다운스트림으로 채택하기 전에 다른 제공된 테마를 현재 선택 항목과 비교하십시오.',
    unsupportedTitle: '지원되지 않는 차선 경계',
    unsupportedDescription: '지원되지 않는 로컬 테마 레인은 병렬 디자인 시스템 권한을 생성하므로 정책 및 규정 준수에 의해 차단됩니다.',
    doNotCreateTitle: '로컬 브랜딩 레이어 도우미를 만들지 마세요.',
    doNotCreateDescription: '소비자에게 브랜드 표현이 필요한 경우 createPublicBrandTheme(...)을 사용하세요. 차선이 누락된 경우 로컬에서 확장GdsTheme(...), createTheme(...) 또는 mergeMantineTheme(...) 소유권을 구축하는 대신 GDS에 대해 요청하십시오.',
    approvedRemediation: '승인된 교정',
    prohibitedOwnership: '소유권 금지',
    accentContrastTitle: '악센트 대비',
    accentContrastDescription: '선택한 사전 설정 및 구성표에 대한 임계값을 기준으로 모든 액센트, 음영 및 모드를 측정합니다.',
    previewBestFor: '가장 적합한 대상:',
    previewColorScheme: '색 구성표:',
    previewA11yProof: '접근성 증명:',
    previewA11yDescription: '상태는 색상만 사용하는 것이 아니라 텍스트, 배지 레이블 및 배치를 사용합니다.',
    forcedDarkPreview: '이 레인은 선택한 색 구성표로 미리보기하므로 런타임은 승인된 대비 계약 내에서 유지됩니다.',
    tokenControls: '토큰 기반 제어',
    referenceInput: '기준 입력',
    referenceInputDescription: '입력은 경로 로컬 스타일로 표류하는 대신 테마 레인 내부에 유지됩니다.',
    referenceInputPlaceholder: '경로 이름을 검색하거나 입력하세요.',
    success: '성공',
    warning: '경고',
    critical: '비판적인',
    proofSurfaceTitle: '참고 부위 교정 표면',
    proofSurfaceDescription: '이 미리보기는 문서 전용 스타일링 레인이 아닌 실제 제공되는 디자인 시스템 런타임을 사용합니다.',
    inspectRoute: '경로 점검',
    metadataRuntimeLane: '런타임 레인',
    metadataColorScheme: '색 구성표',
    metadataA11yProof: 'A11y 증명',
    metadataA11yValue: '키보드 + 읽을 수 있는 상태',
    appsAlignedWith: '다음과 일치하는 앱',
    generalAdoptionWith: '일반 제품 채택',
    avoidLocalTheme: '로컬 비정규 테마 권한을 생성하지 마세요.',
    schemes: { light: '빛', dark: '어두운', auto: '자동' },
    schemeDescriptions: {
      light: '밝은 배경에 대해 읽을 수 있는 기본 표면, 컨트롤, 배지 및 포커스 상태를 확인합니다.',
      dark: '다크 모드가 활성화된 경우 공개, 운영 및 피드백 표면에 대한 대비를 확인합니다.',
      auto: '공급자 계약을 변경하지 않고 유지하면서 OS 제어 체계에 대한 채택 경로를 문서화합니다.',
    },
    presetLabels: {
      default: '기본 런타임 테마',
      '어둠의 대중': '어두운 공개 테마',
      '평평한 표면': '평면 테마',
      editorial: '편집 세리프 테마',
      brand: '브랜드 테마 생성기',
      sunset: '일몰 펄스',
      oceanic: '해양파',
      forest: '산림신호',
      ruby: '루비 스파크',
      amber: '호박색 빛',
      '네온밤': '네온 나이트',
      skyline: '스카이라인 인디고',
      aurora: '오로라 청록색',
      coral: '산호 꽃',
      mint: '민트 서킷',
      orchid: '난초 신호',
      royal: '로얄바이올렛',
      cosmic: '우주 폭발',
      '운동선수-골드': '선수 골드',
    },
    presetSummaries: {
      default: '균형 잡힌 중립 기준선 차선.',
      '어둠의 대중': '어둠 우선 공개 프레젠테이션 레인.',
      '평평한 표면': '낮은 고도의 운영 차선.',
      editorial: '세리프 헤드라인이 있는 읽기 중심의 차선입니다.',
      brand: '관리되는 브랜드 구성 레인.',
      sunset: '따뜻한 오렌지-마젠타색의 생생한 레인.',
      oceanic: '시원한 청록색의 활기찬 레인.',
      forest: '천연 에메랄드가 주도하는 생동감 넘치는 레인.',
      ruby: '강한 빨간색 고대비 차선.',
      amber: '골든 에너지 레인.',
      '네온밤': '라임 액센트의 생동감 넘치는 레인.',
      skyline: '인디고 기술이 앞선 차선.',
      aurora: '낙관적인 제품 표면을 위한 신선한 청록색 앱 레인.',
      coral: '크리에이터, 커머스, 소셜 제품을 위한 표현력이 풍부한 핑크 산호색 레인입니다.',
      mint: '건강, 학습, 성장 제품을 위한 깨끗한 그린민트 레인입니다.',
      orchid: '편집, 문화, 프리미엄 도구를 위한 보라색 포도 레인입니다.',
      royal: 'SaaS 대시보드 및 전문 앱을 위한 자신감 있는 보라색 레인.',
      cosmic: '대담한 공개 앱과 실행 표면을 위한 채도가 높은 파란색-보라색-청록색-자홍색 쇼케이스 레인입니다.',
      '운동선수-골드': '메탈릭 골드 액센트가 있는 프리미엄 블랙 앤 골드 퍼포먼스 레인입니다.',
    },
  },
    ja: {
    themeLabTitle: 'テーマラボ',
    themeLabDescription: '実際に出荷された GDS テーマ プリセット、カラー スキームの動作、および管理されたブランド テーマ ジェネレーターをテストします。このページはライブプルーフの一部であり、個別のスタイリング実験ではありません。',
    themePresetTitle: 'テーマのプリセット',
    presetLabel: 'プリセット',
    previewColorSchemeLabel: 'カラースキームのプレビュー',
    webfontLaneLabel: 'ウェブフォントレーン',
    resetThemeLab: 'テーマラボをリセット',
    shellBehavior: 'テーマの変更は公式サイトのシェルに適用されるため、訪問者は実際のページ全体の実行時の動作を検証できます。',
    brandOptionsTitle: 'ブランドビルダーのオプション',
    brandPrimaryColorLabel: 'ブランドの原色',
    useFlatSurfaces: '平らな面を使用する',
    useEditorialSerif: '社説のセリフ見出しを使用する',
    generatorDescription: 'ジェネレーターは、Web サイト内に 2 番目のテーマ オーソリティーを作成する代わりに、付属のヘルパーを構成します。',
    currentSelectionTitle: '現在の選択の概要',
    bestFor: '以下に最適:',
    runtimeLane: 'ランタイムレーン:',
    colorScheme: '配色：',
    darkForwardNotice: 'この鮮やかなプリセットは、ライブ プレビュー内で選択した配色でレンダリングされます。',
    compareToggle: '2 番目に出荷されたプリセットと比較する',
    comparisonPresetLabel: '比較プリセット',
    shippedLanesTitle: '出荷されたテーマレーン',
    shippedLanesDescription: '以下の各レーンはサポートされているランタイム プリセットです。カラフルなレーンは、ビットマップ背景ではなく、完全な CSS ベースの VibeTheme (キャンバス、シェル、サーフェス、コントロール、フォーカス、アクセント トークン) として出荷されます。',
    selected: '選択済み',
    cssVibeTheme: 'CSS バイブテーマ',
    previewVibe: 'この雰囲気をプレビューする',
    avoidFor: '以下の場合は避けてください。',
    noSpecialExclusion: 'このレーンには特別な除外は記載されていません。',
    athleteGoldReferenceTitle: 'アスリートゴールド基準面',
    athleteGoldReferenceDescription: '同梱されている Athlete Gold VibeTheme トークンをベースにした、より強力なメタリックゴールドを使用した黒のパフォーマンス ナビゲーション。',
    vibeContractTitle: '現在の VibeTheme 契約',
    vibeContractDescription: '選択したプリセットは、これらのパッケージ所有の CSS トークンをエクスポートします。消費者は、GDS テーマの所有権を維持しながら、表現力豊かな製品表面をレンダリングできます。',
    tokenLabels: ['主要な', 'アクセント', 'ライトキャンバス', 'ダークキャンバス', '光の表面', '暗い表面'],
    proofTitle: '明暗自動校正',
    proofDescription: 'すべての公式レーンは、明示的なライト、明示的なダーク、および OS 制御の自動モードにわたって使用可能な状態を維持する必要があります。ダークパブリック レーンは、コントラスト契約を維持するために、プレビューで意図的に暗くする必要があります。',
    requiredProof: '必要な証明: 意味論的なテキスト、可視フォーカス、およびコントラストセーフ状態の処理。',
    livePreviewTitle: 'ライブテーマのプレビュー',
    livePreviewDescription: '訪問者は、出荷されたプリセットをテストし、レーンを比較し、各テーマに基づいて実際の G​​DS サーフェスを検査することができます。',
    comparisonPreviewTitle: '比較プレビュー面',
    comparisonPreviewDescription: 'ダウンストリームに採用する前に、出荷された別のテーマを現在の選択内容と比較します。',
    unsupportedTitle: 'サポートされていない車線境界',
    unsupportedDescription: 'サポートされていないローカル テーマ レーンは、並列デザイン システム権限を作成するため、ポリシーとコンプライアンスによってブロックされます。',
    doNotCreateTitle: 'ローカルのブランディング層ヘルパーを作成しないでください',
    doNotCreateDescription: '消費者がブランド表現を必要とする場合は、createPublicBrandTheme(...) を使用します。レーンが欠落している場合は、extendGdsTheme(...)、createTheme(...)、または mergeMantineTheme(...) の所有権をローカルに構築するのではなく、GDS に対してレーンをリクエストします。',
    approvedRemediation: '承認された修復',
    prohibitedOwnership: '所有権の禁止',
    accentContrastTitle: 'アクセントコントラスト',
    accentContrastDescription: 'すべてのアクセント、シェード、モードは、選択したプリセットとスキームのしきい値と比較して測定されます。',
    previewBestFor: '以下に最適:',
    previewColorScheme: '配色：',
    previewA11yProof: 'アクセシビリティの証明:',
    previewA11yDescription: 'ステータスでは、色だけではなく、テキスト、バッジのラベル、配置が使用されます。',
    forcedDarkPreview: 'このレーンは選択した配色でプレビューされるため、ランタイムは認可されたコントラスト契約内に留まります。',
    tokenControls: 'トークンベースのコントロール',
    referenceInput: '基準入力',
    referenceInputDescription: '入力はルートローカルのスタイルに流れ込むのではなく、テーマレーン内に留まります。',
    referenceInputPlaceholder: 'ルート名を検索または入力します',
    success: '成功',
    warning: '警告',
    critical: '致命的',
    proofSurfaceTitle: '参照サイトの証明面',
    proofSurfaceDescription: 'このプレビューでは、ドキュメントのみのスタイリング レーンではなく、実際に出荷されているデザイン システム ランタイムを使用します。',
    inspectRoute: 'ルートの検査',
    metadataRuntimeLane: 'ランタイムレーン',
    metadataColorScheme: '配色',
    metadataA11yProof: 'A11y プルーフ',
    metadataA11yValue: 'キーボード + 読み取り可能な状態',
    appsAlignedWith: '連携するアプリ',
    generalAdoptionWith: '一般的な製品採用',
    avoidLocalTheme: 'ローカルの非正規テーマの権威を作成することは避けてください。',
    schemes: { light: 'ライト', dark: '暗い', auto: '自動' },
    schemeDescriptions: {
      light: '明るい背景に対して、読み取り可能なデフォルトのサーフェス、コントロール、バッジ、およびフォーカスの状態を検証します。',
      dark: 'ダーク モードがアクティブな場合、パブリック サーフェス、操作サーフェス、およびフィードバック サーフェスのコントラストを検証します。',
      auto: 'プロバイダー契約を変更せずに、OS 制御スキームのアダプター パスを文書化します。',
    },
    presetLabels: {
      default: 'デフォルトのランタイムテーマ',
      'ダークパブリック': 'ダークなパブリックテーマ',
      '平面': '平面テーマ',
      editorial: '社説セリフのテーマ',
      brand: 'ブランドテーマジェネレーター',
      sunset: 'サンセットパルス',
      oceanic: '海洋の波',
      forest: '森林信号機',
      ruby: 'ルビースパーク',
      amber: '琥珀色の輝き',
      'ネオンの夜': 'ネオンの夜',
      skyline: 'スカイラインインディゴ',
      aurora: 'オーロラティール',
      coral: 'サンゴブルーム',
      mint: 'ミントサーキット',
      orchid: '蘭信号',
      royal: 'ロイヤルバイオレット',
      cosmic: 'コズミックバースト',
      'アスリートゴールド': 'アスリートゴールド',
    },
    presetSummaries: {
      default: 'バランスの取れたニュートラルなベースラインレーン。',
      'ダークパブリック': 'ダークファーストのパブリック プレゼンテーション レーン。',
      '平面': '低標高の運用レーン。',
      editorial: 'セリフ見出しのある読書中心のレーン。',
      brand: '管理されたブランド構成レーン。',
      sunset: '温かみのあるオレンジとマゼンタの鮮やかなレーン。',
      oceanic: 'クールなシアンブルーの鮮やかなレーン。',
      forest: '天然エメラルドに導かれた活気に満ちたレーン。',
      ruby: '強い赤のハイコントラストレーン。',
      amber: '黄金のエネルギッシュなレーン。',
      'ネオンの夜': 'ライムがアクセントの鮮やかなレーン。',
      skyline: 'インディゴテクノロジーの前進レーン。',
      aurora: '楽観的な製品表面のための新鮮なティールシアンのアプリレーン。',
      coral: 'クリエイター、コマース、ソーシャル製品向けの表現力豊かなピンクコーラルのレーン。',
      mint: '健康、学習、成長製品を扱うきれいなグリーン ミント レーン。',
      orchid: '編集、カルチャー、プレミアム ツール用の紫色のブドウのレーン。',
      royal: 'SaaS ダッシュボードとプロフェッショナル アプリ向けの自信に満ちたバイオレット レーン。',
      cosmic: '大胆なパブリック アプリと起動面用の、彩度の高い青、紫、シアン、マゼンタのショーケース レーン。',
      'アスリートゴールド': 'メタリックゴールドのアクセントを備えたプレミアムブラック＆ゴールドのパフォーマンスレーン。',
    },
  },
};

const partialReferenceThemeExplorerCopyOverrides = {
  fr: {
    themeLabTitle: 'Laboratoire de thèmes',
    themeLabDescription: 'Testez les presets de thème GDS livrés, le comportement des modes couleur et le générateur de thème de marque gouverné. Cette page fait partie de la démo live, pas d’une expérimentation de style séparée.',
    themePresetTitle: 'Preset de thème',
    presetLabel: 'Preset de thème',
    previewColorSchemeLabel: 'Mode couleur de prévisualisation',
    webfontLaneLabel: 'Lane de police web',
    resetThemeLab: 'Réinitialiser le laboratoire',
    shellBehavior: 'Les changements de thème s’appliquent au shell officiel du site pour vérifier le comportement réel de toute la page.',
    brandOptionsTitle: 'Options du générateur de marque',
    brandPrimaryColorLabel: 'Couleur principale de marque',
    useFlatSurfaces: 'Utiliser des surfaces plates',
    useEditorialSerif: 'Utiliser des titres éditoriaux avec empattement',
    generatorDescription: 'Le générateur compose les helpers livrés au lieu de créer une seconde autorité de thème dans le site.',
    currentSelectionTitle: 'Résumé de la sélection',
    bestFor: 'Idéal pour :',
    runtimeLane: 'Lane runtime :',
    colorScheme: 'Mode couleur :',
    darkForwardNotice: 'Ce preset vibrant s’affiche toujours en le mode sélectionné dans la prévisualisation live.',
    compareToggle: 'Comparer avec un second preset livré',
    comparisonPresetLabel: 'Preset de comparaison',
    shippedLanesTitle: 'Lanes de thème livrées',
    selected: 'Sélectionné',
    previewVibe: 'Prévisualiser ce vibe',
    avoidFor: 'À éviter pour :',
    vibeContractTitle: 'Contrat VibeTheme actuel',
    proofTitle: 'Preuve clair, sombre et auto',
    livePreviewTitle: 'Prévisualisation live du thème',
    comparisonPreviewTitle: 'Surface de prévisualisation comparative',
    unsupportedTitle: 'Limite des lanes non prises en charge',
    doNotCreateTitle: 'Ne créez pas de helpers locaux de branding',
    approvedRemediation: 'Correction approuvée',
    prohibitedOwnership: 'Ownership interdite',
    accentContrastTitle: 'Contraste des accents',
    accentContrastDescription: 'Chaque accent, nuance et mode mesuré par rapport à son seuil pour le préréglage et le schéma sélectionnés.',
    tokenControls: 'Contrôles basés sur les tokens',
    referenceInput: 'Champ de référence',
    referenceInputPlaceholder: 'Rechercher ou saisir un nom de route',
    success: 'Succès',
    warning: 'Avertissement',
    critical: 'Critique',
    inspectRoute: 'Inspecter la route',
    appsAlignedWith: 'Applications alignées avec',
    generalAdoptionWith: 'Adoption produit générale avec',
    avoidLocalTheme: 'Évitez de créer une autorité de thème locale non canonique.',
    schemes: { light: 'Clair', dark: 'Sombre', auto: 'Auto' },
    tokenLabels: ['Primaire', 'Accent', 'Canvas clair', 'Canvas sombre', 'Surface claire', 'Surface sombre'],
    presetLabels: {
      default: 'Thème runtime par défaut',
      'dark-public': 'Thème public sombre',
      'flat-surface': 'Thème de surface plate',
      editorial: 'Thème éditorial avec empattement',
      brand: 'Générateur de thème de marque',
    },
  },
  it: {
    themeLabTitle: 'Laboratorio temi',
    themeLabDescription: 'Testa i preset tema GDS rilasciati, il comportamento degli schemi colore e il generatore brand-theme governato. Questa pagina fa parte della demo live, non è un esperimento di stile separato.',
    themePresetTitle: 'Preset tema',
    presetLabel: 'Preset tema',
    previewColorSchemeLabel: 'Schema colore anteprima',
    webfontLaneLabel: 'Lane webfont',
    resetThemeLab: 'Reimposta laboratorio temi',
    brandOptionsTitle: 'Opzioni brand builder',
    brandPrimaryColorLabel: 'Colore primario brand',
    useFlatSurfaces: 'Usa superfici flat',
    useEditorialSerif: 'Usa titoli serif editoriali',
    currentSelectionTitle: 'Riepilogo selezione corrente',
    bestFor: 'Ideale per:',
    runtimeLane: 'Lane runtime:',
    colorScheme: 'Schema colore:',
    compareToggle: 'Confronta con un secondo preset rilasciato',
    comparisonPresetLabel: 'Preset di confronto',
    shippedLanesTitle: 'Theme lane rilasciate',
    selected: 'Selezionato',
    previewVibe: 'Anteprima vibe',
    avoidFor: 'Evita per:',
    vibeContractTitle: 'Contratto VibeTheme corrente',
    proofTitle: 'Verifica light, dark e auto',
    livePreviewTitle: 'Anteprima tema live',
    comparisonPreviewTitle: 'Superficie anteprima confronto',
    unsupportedTitle: 'Confine lane non supportate',
    doNotCreateTitle: 'Non creare helper locali per il branding layer',
    approvedRemediation: 'Rimedio approvato',
    prohibitedOwnership: 'Ownership vietata',
    accentContrastTitle: 'Contrasto degli accenti',
    accentContrastDescription: 'Ogni accento, tonalità e modalità misurato rispetto alla sua soglia per il preset e lo schema selezionati.',
    referenceInput: 'Input di riferimento',
    success: 'Successo',
    warning: 'Avviso',
    critical: 'Critico',
    inspectRoute: 'Ispeziona route',
    appsAlignedWith: 'App allineate a',
    generalAdoptionWith: 'Adozione prodotto generale con',
    avoidLocalTheme: 'Evita di creare una autorità tema locale non canonica.',
    schemes: { light: 'Chiaro', dark: 'Scuro', auto: 'Auto' },
    tokenLabels: ['Primario', 'Accento', 'Canvas chiaro', 'Canvas scuro', 'Superficie chiara', 'Superficie scura'],
    presetLabels: {
      default: 'Tema runtime predefinito',
      'dark-public': 'Tema pubblico scuro',
      'flat-surface': 'Tema superficie flat',
      editorial: 'Tema editoriale serif',
      brand: 'Generatore tema brand',
    },
  },
  ru: {
    themeLabTitle: 'Лаборатория тем',
    themePresetTitle: 'Пресет темы',
    presetLabel: 'Пресет темы',
    previewColorSchemeLabel: 'Цветовая схема предпросмотра',
    webfontLaneLabel: 'Линия веб-шрифта',
    resetThemeLab: 'Сбросить лабораторию тем',
    brandOptionsTitle: 'Настройки бренд-билдера',
    brandPrimaryColorLabel: 'Основной цвет бренда',
    useFlatSurfaces: 'Использовать плоские поверхности',
    useEditorialSerif: 'Использовать редакционные serif-заголовки',
    currentSelectionTitle: 'Сводка текущего выбора',
    bestFor: 'Лучше всего для:',
    runtimeLane: 'Runtime-линия:',
    colorScheme: 'Цветовая схема:',
    compareToggle: 'Сравнить со вторым поставляемым пресетом',
    comparisonPresetLabel: 'Пресет сравнения',
    shippedLanesTitle: 'Поставляемые линии тем',
    selected: 'Выбрано',
    previewVibe: 'Предпросмотр vibe',
    avoidFor: 'Избегать для:',
    vibeContractTitle: 'Текущий контракт VibeTheme',
    proofTitle: 'Проверка light, dark и auto',
    livePreviewTitle: 'Живой предпросмотр темы',
    comparisonPreviewTitle: 'Поверхность сравнения',
    unsupportedTitle: 'Граница неподдерживаемых линий',
    doNotCreateTitle: 'Не создавайте локальные helper-слои брендинга',
    approvedRemediation: 'Одобренное исправление',
    prohibitedOwnership: 'Запрещённая ownership',
    accentContrastTitle: 'Контраст акцентов',
    accentContrastDescription: 'Каждый акцент, оттенок и режим измеряется относительно своего порога для выбранного пресета и схемы.',
    referenceInput: 'Контрольный ввод',
    success: 'Успех',
    warning: 'Предупреждение',
    critical: 'Критично',
    inspectRoute: 'Проверить маршрут',
    appsAlignedWith: 'Приложения, согласованные с',
    generalAdoptionWith: 'Общее внедрение продукта с',
    avoidLocalTheme: 'Не создавайте локальную неканоническую авторитетность темы.',
    schemes: { light: 'Светлая', dark: 'Тёмная', auto: 'Авто' },
    tokenLabels: ['Основной', 'Акцент', 'Светлый canvas', 'Тёмный canvas', 'Светлая поверхность', 'Тёмная поверхность'],
    presetLabels: {
      default: 'Стандартная runtime-тема',
      'dark-public': 'Тёмная публичная тема',
      'flat-surface': 'Тема плоских поверхностей',
      editorial: 'Редакционная serif-тема',
      brand: 'Генератор бренд-темы',
    },
  },
  he: {
    themeLabTitle: 'מעבדת ערכות נושא',
    themePresetTitle: 'Preset של ערכת נושא',
    presetLabel: 'Preset של ערכת נושא',
    previewColorSchemeLabel: 'מצב צבע לתצוגה מקדימה',
    webfontLaneLabel: 'נתיב פונט רשת',
    resetThemeLab: 'איפוס מעבדת התמות',
    brandOptionsTitle: 'אפשרויות בונה המותג',
    brandPrimaryColorLabel: 'צבע מותג ראשי',
    useFlatSurfaces: 'שימוש במשטחים שטוחים',
    useEditorialSerif: 'שימוש בכותרות serif עריכתיות',
    currentSelectionTitle: 'סיכום הבחירה הנוכחית',
    bestFor: 'מתאים ביותר ל:',
    runtimeLane: 'נתיב runtime:',
    colorScheme: 'מצב צבע:',
    compareToggle: 'השוואה מול preset מסופק נוסף',
    comparisonPresetLabel: 'Preset להשוואה',
    shippedLanesTitle: 'נתיבי תמה שסופקו',
    selected: 'נבחר',
    previewVibe: 'תצוגת vibe',
    avoidFor: 'להימנע עבור:',
    vibeContractTitle: 'חוזה VibeTheme נוכחי',
    proofTitle: 'הוכחת בהיר, כהה ואוטומטי',
    livePreviewTitle: 'תצוגה מקדימה חיה של תמה',
    comparisonPreviewTitle: 'משטח תצוגת השוואה',
    unsupportedTitle: 'גבול נתיבים לא נתמכים',
    doNotCreateTitle: 'לא ליצור helpers מקומיים לשכבת מותג',
    approvedRemediation: 'תיקון מאושר',
    prohibitedOwnership: 'Ownership אסור',
    accentContrastTitle: 'ניגודיות הדגשים',
    accentContrastDescription: 'כל הדגשה, גוון ומצב נמדדים מול הסף שלהם עבור הערכה והסכימה שנבחרו.',
    referenceInput: 'שדה ייחוס',
    success: 'הצלחה',
    warning: 'אזהרה',
    critical: 'קריטי',
    inspectRoute: 'בדיקת route',
    appsAlignedWith: 'אפליקציות המיושרות עם',
    generalAdoptionWith: 'אימוץ מוצר כללי עם',
    avoidLocalTheme: 'אין ליצור סמכות תמה מקומית שאינה קנונית.',
    schemes: { light: 'בהיר', dark: 'כהה', auto: 'אוטומטי' },
    tokenLabels: ['ראשי', 'הדגשה', 'Canvas בהיר', 'Canvas כהה', 'משטח בהיר', 'משטח כהה'],
    presetLabels: {
      default: 'תמת runtime ברירת מחדל',
      'dark-public': 'תמה ציבורית כהה',
      'flat-surface': 'תמת משטח שטוח',
      editorial: 'תמה עריכתית serif',
      brand: 'מחולל תמת מותג',
    },
  },
  ar: {
    themeLabTitle: 'مختبر الثيمات',
    themePresetTitle: 'إعداد الثيم',
    presetLabel: 'إعداد الثيم',
    previewColorSchemeLabel: 'نظام ألوان المعاينة',
    webfontLaneLabel: 'مسار خط الويب',
    resetThemeLab: 'إعادة ضبط مختبر الثيمات',
    brandOptionsTitle: 'خيارات منشئ العلامة',
    brandPrimaryColorLabel: 'لون العلامة الأساسي',
    useFlatSurfaces: 'استخدام أسطح مسطحة',
    useEditorialSerif: 'استخدام عناوين serif تحريرية',
    currentSelectionTitle: 'ملخص الاختيار الحالي',
    bestFor: 'الأفضل لـ:',
    runtimeLane: 'مسار runtime:',
    colorScheme: 'نظام الألوان:',
    compareToggle: 'المقارنة مع إعداد ثانٍ مسلّم',
    comparisonPresetLabel: 'إعداد المقارنة',
    shippedLanesTitle: 'مسارات الثيم المسلّمة',
    selected: 'محدد',
    previewVibe: 'معاينة هذا vibe',
    avoidFor: 'تجنب لـ:',
    vibeContractTitle: 'عقد VibeTheme الحالي',
    proofTitle: 'إثبات الفاتح والداكن والتلقائي',
    livePreviewTitle: 'معاينة الثيم الحية',
    comparisonPreviewTitle: 'سطح معاينة المقارنة',
    unsupportedTitle: 'حدود المسارات غير المدعومة',
    doNotCreateTitle: 'لا تنشئ helpers محلية لطبقة العلامة',
    approvedRemediation: 'معالجة معتمدة',
    prohibitedOwnership: 'ملكية محظورة',
    accentContrastTitle: 'تباين الألوان المميزة',
    accentContrastDescription: 'يُقاس كل لون مميز ودرجة ووضع مقابل عتبته للنمط والمخطط المحددين.',
    referenceInput: 'حقل مرجعي',
    success: 'نجاح',
    warning: 'تحذير',
    critical: 'حرج',
    inspectRoute: 'فحص المسار',
    appsAlignedWith: 'تطبيقات متوافقة مع',
    generalAdoptionWith: 'اعتماد منتج عام مع',
    avoidLocalTheme: 'تجنب إنشاء سلطة ثيم محلية غير معيارية.',
    schemes: { light: 'فاتح', dark: 'داكن', auto: 'تلقائي' },
    tokenLabels: ['أساسي', 'تمييز', 'Canvas فاتح', 'Canvas داكن', 'سطح فاتح', 'سطح داكن'],
    presetLabels: {
      default: 'ثيم runtime الافتراضي',
      'dark-public': 'ثيم عام داكن',
      'flat-surface': 'ثيم سطح مسطح',
      editorial: 'ثيم تحريري serif',
      brand: 'مولّد ثيم العلامة',
    },
  },
};

const explorerGeneratedLocalePacks = {
  es: {
    shippedLanesDescription: 'Cada carril siguiente es un preset runtime compatible. Los carriles coloridos se entregan como VibeThemes basados en CSS: tokens de canvas, shell, superficie, control, foco y acento, no fondos bitmap.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'No hay una exclusión especial indicada para este carril.',
    vibeContractDescription: 'El preset seleccionado exporta estos tokens CSS propiedad del paquete. Los consumidores pueden renderizar superficies expresivas sin salir de la propiedad temática de GDS.',
    proofDescription: 'Cada carril oficial debe seguir siendo usable en modo claro explícito, oscuro explícito y automático controlado por el sistema operativo.',
    requiredProof: 'Prueba requerida: texto semántico, foco visible y estados con contraste seguro.',
    livePreviewDescription: 'Los visitantes pueden probar presets entregados, comparar carriles e inspeccionar superficies GDS reales bajo cada tema.',
    comparisonPreviewDescription: 'Compare otro tema entregado con la selección actual antes de adoptarlo downstream.',
    unsupportedDescription: 'Los carriles de tema locales no compatibles se bloquean por política y cumplimiento porque crean autoridad paralela de diseño.',
    doNotCreateDescription: 'Si un consumidor necesita expresión de marca, use createPublicBrandTheme(...). Si falta un carril, solicítelo para GDS en lugar de crear ownership local.',
    previewBestFor: 'Mejor para:',
    previewColorScheme: 'Esquema de color:',
    previewA11yProof: 'Prueba de accesibilidad:',
    previewA11yDescription: 'el estado usa texto, etiqueta de badge y ubicación, no solo color.',
    forcedDarkPreview: 'Este carril se previsualiza en el esquema seleccionado para mantener el contrato de contraste aprobado.',
    tokenControls: 'Controles basados en tokens',
    referenceInputDescription: 'Las entradas permanecen dentro del carril de tema en lugar de derivar a estilos locales de ruta.',
    metadataRuntimeLane: 'Carril runtime',
    metadataColorScheme: 'Esquema de color',
    metadataA11yProof: 'Prueba a11y',
    metadataA11yValue: 'Teclado + estados legibles',
    proofSurfaceTitle: 'Superficie de prueba del sitio de referencia',
    proofSurfaceDescription: 'Esta previsualización usa el runtime real entregado del sistema de diseño, no un carril de estilo solo para docs.',
    schemeDescriptions: {
      light: 'Valida superficies, controles, badges y foco legibles sobre fondos claros.',
      dark: 'Valida contraste para superficies públicas, operativas y de feedback en modo oscuro.',
      auto: 'Documenta el camino de adopción para esquemas controlados por el sistema operativo sin cambiar el contrato del provider.',
    },
    presetSummaries: {
      default: 'Carril base neutral equilibrado.',
      'dark-public': 'Carril público pensado primero para modo oscuro.',
      'flat-surface': 'Carril operativo con menor elevación.',
      editorial: 'Carril enfocado en lectura con titulares serif.',
      brand: 'Carril de composición de marca gobernada.',
      sunset: 'Carril vibrante naranja-magenta cálido.',
      oceanic: 'Carril vibrante cian-azul frío.',
      forest: 'Carril vibrante guiado por esmeralda natural.',
      ruby: 'Carril rojo fuerte de alto contraste.',
      amber: 'Carril dorado energético.',
      'neon-night': 'Carril oscuro con acento lima.',
      skyline: 'Carril índigo orientado a tecnología.',
      aurora: 'Carril teal-cian fresco para superficies optimistas.',
      coral: 'Carril rosa-coral expresivo para creator, comercio y social.',
      mint: 'Carril verde menta limpio para salud, aprendizaje y crecimiento.',
      orchid: 'Carril púrpura-uva para editorial, cultura y herramientas premium.',
      royal: 'Carril violeta seguro para dashboards SaaS y apps profesionales.',
      cosmic: 'Carril showcase azul-violeta-cian-magenta saturado para lanzamientos audaces.',
    },
  },
  fr: {
    shippedLanesDescription: 'Chaque lane ci-dessous est un preset runtime pris en charge. Les lanes colorées sont livrées comme VibeThemes CSS complets avec tokens de canvas, shell, surface, contrôle, focus et accent.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'Aucune exclusion spéciale n’est indiquée pour cette lane.',
    vibeContractDescription: 'Le preset sélectionné exporte ces tokens CSS possédés par le package. Les consommateurs peuvent rendre des surfaces expressives tout en restant dans la gouvernance GDS.',
    proofDescription: 'Chaque lane officielle doit rester utilisable en mode clair explicite, sombre explicite et auto contrôlé par le système.',
    requiredProof: 'Preuve requise : texte sémantique, focus visible et états sûrs en contraste.',
    livePreviewDescription: 'Les visiteurs peuvent tester les presets livrés, comparer les lanes et inspecter de vraies surfaces GDS sous chaque thème.',
    comparisonPreviewDescription: 'Comparez un autre thème livré avec la sélection actuelle avant adoption downstream.',
    unsupportedDescription: 'Les lanes de thème locales non prises en charge sont bloquées par la politique et la conformité.',
    doNotCreateDescription: 'Si un consommateur a besoin d’expression de marque, utilisez createPublicBrandTheme(...). Si une lane manque, demandez-la à GDS au lieu de créer une ownership locale.',
    previewBestFor: 'Idéal pour :',
    previewColorScheme: 'Mode couleur :',
    previewA11yProof: 'Preuve d’accessibilité :',
    previewA11yDescription: 'le statut utilise texte, libellé de badge et placement, pas seulement la couleur.',
    forcedDarkPreview: 'Cette lane est toujours prévisualisée en le mode sélectionné pour préserver son contrat de contraste.',
    referenceInputDescription: 'Les champs restent dans la lane de thème au lieu de dériver vers du style local.',
    metadataRuntimeLane: 'Lane runtime',
    metadataColorScheme: 'Mode couleur',
    metadataA11yProof: 'Preuve a11y',
    metadataA11yValue: 'Clavier + états lisibles',
    proofSurfaceTitle: 'Surface de preuve du site de référence',
    proofSurfaceDescription: 'Cette prévisualisation utilise le vrai runtime livré du design system.',
  },
  it: {
    shippedLanesDescription: 'Ogni lane sotto è un preset runtime supportato. Le lane colorate sono VibeTheme CSS completi con token canvas, shell, superficie, controllo, focus e accento.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'Nessuna esclusione speciale indicata per questa lane.',
    vibeContractDescription: 'Il preset selezionato esporta questi token CSS di proprietà del package. I consumer possono renderizzare superfici espressive restando nella governance GDS.',
    proofDescription: 'Ogni lane ufficiale deve restare usabile in modalità chiara, scura e automatica controllata dal sistema.',
    requiredProof: 'Prova richiesta: testo semantico, focus visibile e stati con contrasto sicuro.',
    livePreviewDescription: 'I visitatori possono testare preset rilasciati, confrontare lane e ispezionare superfici GDS reali.',
    comparisonPreviewDescription: 'Confronta un altro tema rilasciato con la selezione corrente prima dell’adozione downstream.',
    unsupportedDescription: 'Le lane tema locali non supportate sono bloccate da policy e compliance.',
    doNotCreateDescription: 'Se serve espressione di brand, usa createPublicBrandTheme(...). Se manca una lane, richiedila a GDS invece di creare ownership locale.',
    previewBestFor: 'Ideale per:',
    previewColorScheme: 'Schema colore:',
    previewA11yProof: 'Prova accessibilità:',
    previewA11yDescription: 'lo stato usa testo, etichetta badge e posizione, non solo colore.',
    forcedDarkPreview: 'Questa lane viene mostrata nello schema colore selezionato per mantenere il contratto di contrasto.',
    tokenControls: 'Controlli basati su token',
    referenceInputDescription: 'Gli input restano nella lane tema invece di scivolare in stile locale.',
    referenceInputPlaceholder: 'Cerca o inserisci un nome route',
    metadataRuntimeLane: 'Lane runtime',
    metadataColorScheme: 'Schema colore',
    metadataA11yProof: 'Prova a11y',
    metadataA11yValue: 'Tastiera + stati leggibili',
    proofSurfaceTitle: 'Superficie prova del sito di riferimento',
    proofSurfaceDescription: 'Questa anteprima usa il runtime reale del design system rilasciato.',
  },
  ru: {
    themeLabDescription: 'Проверьте поставляемые пресеты тем GDS, поведение цветовых схем и управляемый генератор бренд-темы. Эта страница является частью live-демо, а не отдельным экспериментом стилей.',
    shellBehavior: 'Изменения темы применяются к официальной оболочке сайта, чтобы посетители могли проверить реальное поведение всей страницы.',
    generatorDescription: 'Генератор компонует поставляемые helper-ы, а не создает вторую власть над темой внутри сайта.',
    darkForwardNotice: 'Этот vibrant пресет всегда отображается в выбранной цветовой схеме в live-предпросмотре.',
    shippedLanesDescription: 'Каждая линия ниже является поддерживаемым runtime-пресетом. Цветные линии поставляются как полные CSS VibeTheme с токенами canvas, shell, surface, control, focus и accent.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'Для этой линии не указано специальное исключение.',
    vibeContractDescription: 'Выбранный пресет экспортирует CSS-токены, принадлежащие пакету. Потребители могут рендерить выразительные поверхности, оставаясь в зоне владения GDS.',
    proofDescription: 'Каждая официальная линия должна оставаться usable в явном светлом, явном темном и системном auto режиме.',
    requiredProof: 'Обязательная проверка: семантический текст, видимый фокус и контрастно-безопасные состояния.',
    livePreviewDescription: 'Посетители могут тестировать поставляемые пресеты, сравнивать линии и проверять реальные поверхности GDS.',
    comparisonPreviewDescription: 'Сравните другую поставляемую тему с текущим выбором перед downstream-внедрением.',
    unsupportedDescription: 'Неподдерживаемые локальные линии тем блокируются политикой и compliance, потому что создают параллельную власть дизайн-системы.',
    doNotCreateDescription: 'Если потребителю нужна выразительность бренда, используйте createPublicBrandTheme(...). Если линии не хватает, запросите ее в GDS.',
    previewBestFor: 'Лучше всего для:',
    previewColorScheme: 'Цветовая схема:',
    previewA11yProof: 'Проверка доступности:',
    previewA11yDescription: 'статус использует текст, подпись badge и размещение, а не только цвет.',
    forcedDarkPreview: 'Эта линия всегда просматривается в выбранной цветовой схеме, чтобы сохранить утвержденный контракт контраста.',
    tokenControls: 'Контролы на токенах',
    referenceInputDescription: 'Поля ввода остаются внутри линии темы, а не уходят в локальные стили маршрута.',
    referenceInputPlaceholder: 'Найдите или введите имя маршрута',
    metadataRuntimeLane: 'Runtime-линия',
    metadataColorScheme: 'Цветовая схема',
    metadataA11yProof: 'A11y-проверка',
    metadataA11yValue: 'Клавиатура + читаемые состояния',
    proofSurfaceTitle: 'Проверочная поверхность reference-сайта',
    proofSurfaceDescription: 'Этот предпросмотр использует реальный поставляемый runtime дизайн-системы.',
  },
  he: {
    themeLabDescription: 'בדקו את preset-י התמה המסופקים של GDS, את התנהגות מצבי הצבע ואת מחולל תמת המותג המנוהל.',
    shellBehavior: 'שינויי תמה חלים על מעטפת האתר הרשמית כדי לאמת התנהגות runtime אמיתית של עמוד שלם.',
    generatorDescription: 'המחולל מרכיב helpers מסופקים במקום ליצור סמכות תמה שנייה באתר.',
    darkForwardNotice: 'Preset זה מוצג תמיד במצב הצבע שנבחר בתצוגה החיה.',
    shippedLanesDescription: 'כל נתיב למטה הוא preset runtime נתמך. נתיבים צבעוניים מסופקים כ-VibeTheme מלא מבוסס CSS עם tokens לקנבס, מעטפת, משטח, בקרה, focus והדגשה.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'לא צוינה החרגה מיוחדת לנתיב זה.',
    vibeContractDescription: 'ה-preset שנבחר מייצא tokens CSS בבעלות החבילה. צרכנים יכולים לרנדר משטחים אקספרסיביים בתוך בעלות GDS.',
    proofDescription: 'כל נתיב רשמי חייב להישאר שמיש במצב בהיר, כהה ואוטומטי.',
    requiredProof: 'הוכחה נדרשת: טקסט סמנטי, focus נראה וטיפול מצב בטוח בקונטרסט.',
    livePreviewDescription: 'מבקרים יכולים לבדוק presets מסופקים, להשוות נתיבים ולבחון משטחי GDS אמיתיים.',
    comparisonPreviewDescription: 'השוו תמה מסופקת נוספת מול הבחירה הנוכחית לפני אימוץ downstream.',
    unsupportedDescription: 'נתיבי תמה מקומיים לא נתמכים נחסמים על ידי מדיניות ו-compliance.',
    doNotCreateDescription: 'אם צרכן צריך ביטוי מותג, השתמשו ב-createPublicBrandTheme(...). אם חסר נתיב, בקשו אותו מ-GDS.',
    previewBestFor: 'מתאים ביותר ל:',
    previewColorScheme: 'מצב צבע:',
    previewA11yProof: 'הוכחת נגישות:',
    previewA11yDescription: 'המצב משתמש בטקסט, תווית badge ומיקום, לא רק צבע.',
    forcedDarkPreview: 'נתיב זה תמיד מוצג במצב הצבע שנבחר כדי לשמור על חוזה הקונטרסט המאושר.',
    tokenControls: 'בקרות מבוססות tokens',
    referenceInputDescription: 'שדות נשארים בתוך נתיב התמה במקום לגלוש לעיצוב מקומי.',
    referenceInputPlaceholder: 'חיפוש או הקלדת שם route',
    metadataRuntimeLane: 'נתיב runtime',
    metadataColorScheme: 'מצב צבע',
    metadataA11yProof: 'הוכחת a11y',
    metadataA11yValue: 'מקלדת + מצבים קריאים',
    proofSurfaceTitle: 'משטח הוכחה של אתר הייחוס',
    proofSurfaceDescription: 'תצוגה זו משתמשת ב-runtime האמיתי של מערכת העיצוב המסופקת.',
  },
  ar: {
    themeLabDescription: 'اختبر إعدادات ثيم GDS المسلّمة وسلوك أنظمة الألوان ومولّد ثيم العلامة المحكوم.',
    shellBehavior: 'تطبّق تغييرات الثيم على غلاف الموقع الرسمي حتى يمكن التحقق من سلوك صفحة كاملة في runtime.',
    generatorDescription: 'يركّب المولّد helpers مسلّمة بدلاً من إنشاء سلطة ثيم ثانية داخل الموقع.',
    darkForwardNotice: 'يعرض هذا الإعداد دائماً في نظام الألوان المحدد داخل المعاينة الحية.',
    shippedLanesDescription: 'كل مسار أدناه هو إعداد runtime مدعوم. المسارات الملونة تُسلّم كـ VibeTheme كامل مبني على CSS مع tokens للوحة والغلاف والسطح والتحكم والتركيز والتمييز.',
    cssVibeTheme: 'CSS VibeTheme',
    noSpecialExclusion: 'لا توجد ملاحظة استثناء خاصة لهذا المسار.',
    vibeContractDescription: 'يصدّر الإعداد المحدد tokens CSS مملوكة للحزمة. يمكن للمستهلكين عرض أسطح معبّرة مع البقاء ضمن ملكية GDS.',
    proofDescription: 'يجب أن يبقى كل مسار رسمي قابلاً للاستخدام في الوضع الفاتح والداكن والتلقائي.',
    requiredProof: 'الإثبات المطلوب: نص دلالي وتركيز مرئي ومعالجة حالة آمنة التباين.',
    livePreviewDescription: 'يمكن للزوار اختبار الإعدادات المسلّمة ومقارنة المسارات وفحص أسطح GDS الحقيقية.',
    comparisonPreviewDescription: 'قارن ثيماً مسلّماً آخر بالاختيار الحالي قبل اعتماده downstream.',
    unsupportedDescription: 'تُحظر مسارات الثيم المحلية غير المدعومة بالسياسة والامتثال لأنها تنشئ سلطة موازية.',
    doNotCreateDescription: 'إذا احتاج المستهلك إلى تعبير علامة، استخدم createPublicBrandTheme(...). إذا كان المسار مفقوداً فاطلبه من GDS.',
    previewBestFor: 'الأفضل لـ:',
    previewColorScheme: 'نظام الألوان:',
    previewA11yProof: 'إثبات الوصول:',
    previewA11yDescription: 'تستخدم الحالة النص وتسمية الشارة والموقع، لا اللون وحده.',
    forcedDarkPreview: 'يُعرض هذا المسار دائماً في نظام الألوان المحدد للحفاظ على عقد التباين المعتمد.',
    tokenControls: 'عناصر تحكم قائمة على tokens',
    referenceInputDescription: 'تبقى المدخلات داخل مسار الثيم بدلاً من الانزلاق إلى تنسيق محلي للمسار.',
    referenceInputPlaceholder: 'ابحث أو أدخل اسم route',
    metadataRuntimeLane: 'مسار runtime',
    metadataColorScheme: 'نظام الألوان',
    metadataA11yProof: 'إثبات a11y',
    metadataA11yValue: 'لوحة مفاتيح + حالات مقروءة',
    proofSurfaceTitle: 'سطح إثبات موقع المرجع',
    proofSurfaceDescription: 'تستخدم هذه المعاينة runtime الحقيقي المسلّم من نظام التصميم.',
  },
} as const;

const referenceThemeExplorerCopyOverrides = Object.fromEntries(
  Array.from(new Set([
    ...Object.keys(partialReferenceThemeExplorerCopyOverrides),
    ...Object.keys(explorerGeneratedLocalePacks),
  ])).map((locale) => {
    const generatedCopy = (explorerGeneratedLocalePacks as Record<string, Record<string, unknown>>)[locale] ?? {};
    const copy = (partialReferenceThemeExplorerCopyOverrides as Record<string, Record<string, unknown>>)[locale] ?? {};
    return [
    locale,
    {
      ...generatedCopy,
      ...copy,
      schemeDescriptions: {
        ...(generatedCopy.schemeDescriptions as Record<string, string> | undefined),
        ...(copy.schemeDescriptions as Record<string, string> | undefined),
      },
      presetSummaries: {
        ...(generatedCopy.presetSummaries as Record<string, string> | undefined),
        ...(copy.presetSummaries as Record<string, string> | undefined),
      },
    },
  ];
  }),
);

export { referenceThemeExplorerCopy, referenceThemeExplorerCopyOverrides };
