export * from '@sovereignsquad/gds-theme/client';
export * from '@sovereignsquad/gds-core/client';
// Issue 556. Both packages surface `GdsDensityMode` — gds-theme declares it (the axis) and
// gds-core re-exports it (the subtree override context). It is ONE type, but two star
// exports of the same name are ambiguous to TypeScript regardless, so the owner is named
// explicitly here rather than dropping it from one barrel and breaking whichever import
// path consumers happen to use.
export type { GdsDensityMode } from '@sovereignsquad/gds-theme/client';
export {
  AppShell,
  ContentOpsActionBar,
  ContentOpsEditor,
  ContentOpsSection,
  DataTable,
  EditorScaffold,
  FormSection,
  InfoCard,
  PageHeader as AdminPageHeader,
  ResponsiveDataView,
  SemanticNavLink,
  StatsStrip,
  WorkspaceHeader,
  AdminTextInput,
  AdminTextarea,
  AdminCheckbox,
  AdminSelect,
  AdminFileUpload,
  AdminFormSection,
  AdminFormStatus,
  AdminFormActions,
  AdminCrudForm,
  AdminDataTable,
  AdminAnalyticsTable,
  AdminModal,
  AdminDetailDrawer,
  AdminReviewLayout,
  AdminResourceManager,
  AdminResourceGrid,
  AdminResourceCard,
  AdminResourceToolbar,
  AdminResourceEmptyState,
} from '@sovereignsquad/gds-admin/client';
export type {
  AppShellProps,
  ContentOpsActionBarProps,
  ContentOpsEditorProps,
  ContentOpsSectionProps,
  DataTableColumn,
  DataTableProps,
  EditorScaffoldProps,
  FormSectionProps,
  InfoCardProps,
  PageHeaderOverflowAction as AdminPageHeaderOverflowAction,
  PageHeaderProps as AdminPageHeaderProps,
  ResponsiveDataViewFilterChip,
  ResponsiveDataViewProps,
  SemanticNavLinkProps,
  StatItem,
  StatsStripProps,
  WorkspaceHeaderProps,
  AdminFieldBaseProps,
  AdminFieldState,
  AdminFormStatusState,
  AdminTextInputProps,
  AdminTextareaProps,
  AdminCheckboxProps,
  AdminSelectProps,
  AdminFileUploadProps,
  AdminFormSectionProps,
  AdminFormStatusProps,
  AdminFormActionsProps,
  AdminCrudFormProps,
  AdminDataTableColumn,
  AdminDataTableProps,
  AdminDataTableSort,
  AdminAnalyticsTableProps,
  AdminOverlayState,
  AdminModalProps,
  AdminDetailDrawerProps,
  AdminReviewLayoutProps,
  AdminResourceState,
  AdminResourceRecord,
  AdminResourceAction,
  AdminResourceManagerProps,
  AdminResourceGridProps,
  AdminResourceCardProps,
  AdminResourceToolbarProps,
  AdminResourceEmptyStateProps,
} from '@sovereignsquad/gds-admin/client';
