// Generated by scripts/generate-component-index.mjs — the complete element list,
// derived from the component census + pattern registry + reviewed exemptions (issue 626).
// Do not edit; regenerate via artifacts:refresh.

export interface GdsComponentIndexRow {
  name: string;
  status: 'registered' | 'exempt';
  home?: { id: string; family: string; section: string };
  alsoAppearsIn?: string[];
  reason?: string;
}

export const gdsComponentIndex: GdsComponentIndexRow[] = [
  {
    "name": "AccentPanel",
    "status": "registered",
    "home": {
      "id": "accent-panels",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AccessRecoveryPanel",
    "status": "registered",
    "home": {
      "id": "access-recovery-panels",
      "family": "access",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AccessSummary",
    "status": "registered",
    "home": {
      "id": "access-summaries",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ActionBar",
    "status": "registered",
    "home": {
      "id": "semantic-actions",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": [
      "action-bar"
    ]
  },
  {
    "name": "ActiveFilterChips",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AdminAnalyticsTable",
    "status": "exempt",
    "reason": "Admin sub-part of the admin/editor-flows patterns — composed admin surface, not a standalone core catalog pattern."
  },
  {
    "name": "AdminCheckbox",
    "status": "exempt",
    "reason": "Admin form control sub-part (AdminForms) — admin-scoped input."
  },
  {
    "name": "AdminCrudForm",
    "status": "exempt",
    "reason": "Admin composite (AdminForms) — CRUD form scaffold, admin-scoped."
  },
  {
    "name": "AdminDataTable",
    "status": "exempt",
    "reason": "Admin composite (AdminDataTable) — admin-scoped data grid; core grid pattern registered via DataTable."
  },
  {
    "name": "AdminDetailDrawer",
    "status": "exempt",
    "reason": "Admin overlay sub-part (AdminOverlays) — admin-scoped drawer."
  },
  {
    "name": "AdminFileUpload",
    "status": "exempt",
    "reason": "Admin form control sub-part (AdminForms) — admin-scoped upload field."
  },
  {
    "name": "AdminFormActions",
    "status": "exempt",
    "reason": "Admin form sub-part (AdminForms) — action bar, admin-scoped."
  },
  {
    "name": "AdminFormSection",
    "status": "exempt",
    "reason": "Admin form sub-part (AdminForms) — section wrapper, admin-scoped."
  },
  {
    "name": "AdminFormStatus",
    "status": "exempt",
    "reason": "Admin form sub-part (AdminForms) — status region, admin-scoped."
  },
  {
    "name": "AdminModal",
    "status": "exempt",
    "reason": "Admin overlay sub-part (AdminOverlays) — admin-scoped modal."
  },
  {
    "name": "AdminResourceCard",
    "status": "exempt",
    "reason": "Admin resource sub-part (AdminResourceManager) — admin-scoped card."
  },
  {
    "name": "AdminResourceEmptyState",
    "status": "exempt",
    "reason": "Admin resource sub-part (AdminResourceManager) — admin-scoped empty state."
  },
  {
    "name": "AdminResourceGrid",
    "status": "exempt",
    "reason": "Admin resource sub-part (AdminResourceManager) — admin-scoped grid."
  },
  {
    "name": "AdminResourceManager",
    "status": "exempt",
    "reason": "Admin composite (AdminResourceManager) — admin-scoped CRUD manager scaffold."
  },
  {
    "name": "AdminResourceToolbar",
    "status": "exempt",
    "reason": "Admin resource sub-part (AdminResourceManager) — admin-scoped toolbar."
  },
  {
    "name": "AdminReviewLayout",
    "status": "exempt",
    "reason": "Admin composite (AdminResourceManager) — admin-scoped review layout."
  },
  {
    "name": "AdminSelect",
    "status": "exempt",
    "reason": "Admin form control sub-part (AdminForms) — admin-scoped select."
  },
  {
    "name": "AdminTextarea",
    "status": "exempt",
    "reason": "Admin form control sub-part (AdminForms) — admin-scoped textarea."
  },
  {
    "name": "AdminTextInput",
    "status": "exempt",
    "reason": "Admin form control sub-part (AdminForms) — admin-scoped text input."
  },
  {
    "name": "AdvancedDataTable",
    "status": "registered",
    "home": {
      "id": "admin-data-table",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AISearchCard",
    "status": "registered",
    "home": {
      "id": "ai-search-card",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AmenityChipGrid",
    "status": "exempt",
    "reason": "Domain sub-part (partner amenities) — chip grid composed into registered partner patterns."
  },
  {
    "name": "AppShell",
    "status": "registered",
    "home": {
      "id": "discovery-shell",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": [
      "admin-app-shell"
    ]
  },
  {
    "name": "ArticleShell",
    "status": "registered",
    "home": {
      "id": "article-shells",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AsyncSurface",
    "status": "registered",
    "home": {
      "id": "state-blocks",
      "family": "feedback",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "AuthShell",
    "status": "registered",
    "home": {
      "id": "auth-shells",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "BannerNotice",
    "status": "registered",
    "home": {
      "id": "alerts",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": [
      "loaders-skeletons"
    ]
  },
  {
    "name": "BodyText",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive composed into registered patterns."
  },
  {
    "name": "BottomTabBar",
    "status": "registered",
    "home": {
      "id": "bottom-tab-navigation",
      "family": "public",
      "section": "Shell & Navigation Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "BoundedPreviewSurface",
    "status": "exempt",
    "reason": "Layout/preview primitive used to bound catalog demos — not itself a catalog pattern."
  },
  {
    "name": "BrowseSurface",
    "status": "registered",
    "home": {
      "id": "browse-surface",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "BulkActionsBar",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "CardTitle",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "ChartTokenPanel",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ChatInput",
    "status": "registered",
    "home": {
      "id": "conversation-surface",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ChatMessage",
    "status": "registered",
    "home": {
      "id": "conversation-surface",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ChatThread",
    "status": "registered",
    "home": {
      "id": "conversation-surface",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ChoiceChip",
    "status": "registered",
    "home": {
      "id": "buttons",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ClippedFlexChild",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — flex-clipping helper, not a catalog pattern."
  },
  {
    "name": "CommandPalette",
    "status": "exempt",
    "reason": "Client-runtime composite (CommandPalette.client) — command surface driven by CommandRegistryProvider (registered on the drawers row)."
  },
  {
    "name": "CommandRegistryProvider",
    "status": "registered",
    "home": {
      "id": "drawers",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ConfirmDialog",
    "status": "registered",
    "home": {
      "id": "modals",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ConsumerDashboardGrid",
    "status": "registered",
    "home": {
      "id": "consumer-dashboard-grid",
      "family": "operations",
      "section": "Dashboard & Panel Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ConsumerSection",
    "status": "registered",
    "home": {
      "id": "consumer-sections",
      "family": "operations",
      "section": "Dashboard & Panel Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ContentOpsActionBar",
    "status": "registered",
    "home": {
      "id": "content-operations-editor",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ContentOpsEditor",
    "status": "registered",
    "home": {
      "id": "content-operations-editor",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ContentOpsSection",
    "status": "registered",
    "home": {
      "id": "content-operations-editor",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "CountBadge",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "CreatorThemeBoundary",
    "status": "exempt",
    "reason": "Provider/context (creator theme scope) — non-visual boundary."
  },
  {
    "name": "CreatorThemeDiagnostics",
    "status": "exempt",
    "reason": "Diagnostics/dev surface (creator theme) — not a consumer-facing catalog pattern."
  },
  {
    "name": "CtaButtonGroup",
    "status": "registered",
    "home": {
      "id": "cta-button-groups",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "DataTable",
    "status": "registered",
    "home": {
      "id": "admin-data-table",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "DataToolbar",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "DetailProfileShell",
    "status": "registered",
    "home": {
      "id": "detail-surfaces",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": [
      "detail-profile-shell"
    ]
  },
  {
    "name": "DiscoveryShell",
    "status": "registered",
    "home": {
      "id": "shell-contracts",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": [
      "discovery-shell"
    ]
  },
  {
    "name": "DocsCodeBlock",
    "status": "registered",
    "home": {
      "id": "docs-code-blocks",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "DocsHeaderActionSelect",
    "status": "exempt",
    "reason": "Sub-part of the registered DocsShell pattern — header action control."
  },
  {
    "name": "DocsPageShell",
    "status": "registered",
    "home": {
      "id": "docs-page-shell",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "DocsShell",
    "status": "registered",
    "home": {
      "id": "shell-contracts",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": [
      "docs-shell"
    ]
  },
  {
    "name": "EditorialCard",
    "status": "registered",
    "home": {
      "id": "editorial-cards",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "EditorialHero",
    "status": "registered",
    "home": {
      "id": "editorial-hero",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "EditorScaffold",
    "status": "registered",
    "home": {
      "id": "editor-scaffold",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "EmptyState",
    "status": "registered",
    "home": {
      "id": "empty-state",
      "family": "feedback",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "EvidencePanel",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FeatureBand",
    "status": "registered",
    "home": {
      "id": "feature-band",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FileUploadField",
    "status": "exempt",
    "reason": "Form field sub-part (GdsSchemaForm file field) — field renderer, not a standalone catalog pattern."
  },
  {
    "name": "FilterChipGroup",
    "status": "registered",
    "home": {
      "id": "buttons",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FilterDrawer",
    "status": "registered",
    "home": {
      "id": "filter-drawer",
      "family": "access",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": [
      "drawers"
    ]
  },
  {
    "name": "FitScoreChip",
    "status": "registered",
    "home": {
      "id": "fit-score-chip",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FloatingActionPlacement",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — positioning helper, not a catalog pattern."
  },
  {
    "name": "FoodMenuSection",
    "status": "registered",
    "home": {
      "id": "food-menu-section",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FormErrorSummary",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FormField",
    "status": "registered",
    "home": {
      "id": "form-field",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "FormSection",
    "status": "registered",
    "home": {
      "id": "form-section",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GameBoardTile",
    "status": "registered",
    "home": {
      "id": "game-board-tile",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsAccentContrastMatrix",
    "status": "registered",
    "home": {
      "id": "accent-contrast-matrix",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsAccessGate",
    "status": "registered",
    "home": {
      "id": "access-gates",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsAdminDashboardTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold, exempt per issue (templates/catalog)."
  },
  {
    "name": "GdsAnalyticsTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsAreaChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsAssetManager",
    "status": "exempt",
    "reason": "Client-runtime composite (GdsAssetManager.client) — asset manager scaffold, not a standalone catalog pattern."
  },
  {
    "name": "GdsAssetPreviewCard",
    "status": "exempt",
    "reason": "Sub-part of GdsAssetManager — asset preview cell, not a standalone catalog pattern."
  },
  {
    "name": "GdsBadge",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": [
      "badges"
    ]
  },
  {
    "name": "GdsBadgeShapeCircle",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeShapeHexagon",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeShapePin",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeShapeRosette",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeShapes",
    "status": "exempt",
    "reason": "Badge shape dictionary (issue 487) — closed name→component lookup mirroring GdsIcons; the six shape components it maps to are registered on the badges pattern."
  },
  {
    "name": "GdsBadgeShapeShield",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeShapeSquircle",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeStack",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBadgeStackLayer",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBarChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the reporting-contracts chart family already registered via GdsChart."
  },
  {
    "name": "GdsBenchmarkBarChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsBleed",
    "status": "exempt",
    "reason": "Layout primitive (bleed) — composed into registered patterns."
  },
  {
    "name": "GdsBox",
    "status": "exempt",
    "reason": "Layout primitive (governed Box) — composed into registered patterns, not itself a catalog pattern."
  },
  {
    "name": "GdsBreadcrumbs",
    "status": "registered",
    "home": {
      "id": "docs-page-shell",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsCalendarHeatmapChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsChartAxis",
    "status": "exempt",
    "reason": "Chart sub-part (GdsChart) — composed inside registered chart wrappers."
  },
  {
    "name": "GdsChartLegend",
    "status": "exempt",
    "reason": "Chart sub-part (GdsChart) — composed inside registered chart wrappers."
  },
  {
    "name": "GdsChartTooltip",
    "status": "exempt",
    "reason": "Chart sub-part (GdsChart) — composed inside registered chart wrappers."
  },
  {
    "name": "GdsCluster",
    "status": "exempt",
    "reason": "Layout primitive (wrapping cluster) — composed into registered patterns."
  },
  {
    "name": "GdsColumnGrid",
    "status": "exempt",
    "reason": "Layout primitive (explicit column grid) — composed into registered patterns, not itself a catalog pattern."
  },
  {
    "name": "GdsColumnGridItem",
    "status": "exempt",
    "reason": "Layout primitive (column-grid track-span child) — composed into registered patterns."
  },
  {
    "name": "GdsConfirmProvider",
    "status": "exempt",
    "reason": "Provider/context (overlay confirm) — non-visual; the confirm pattern is registered via ConfirmDialog."
  },
  {
    "name": "GdsContainer",
    "status": "exempt",
    "reason": "Layout primitive (page container) — composed into registered patterns."
  },
  {
    "name": "GdsContentPatternCatalog",
    "status": "exempt",
    "reason": "Catalog component (GdsContentDesign) — content-pattern index, not a catalog pattern."
  },
  {
    "name": "GdsCountBadge",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsCrudEditorTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsDataTable",
    "status": "exempt",
    "reason": "Client-runtime composite (GdsDataTable.client) — data-grid whose canonical pattern is registered via AdvancedDataTable / DataTable."
  },
  {
    "name": "GdsDateInput",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsDateRangeInput",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsDateTimeInput",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsDensityProvider",
    "status": "exempt",
    "reason": "Provider/context (global density mode) — non-visual; density-aware cards are registered via ProductCard."
  },
  {
    "name": "GdsDesignHandoffCatalog",
    "status": "exempt",
    "reason": "Catalog component (GdsDesignHandoff) — design-handoff index, not a catalog pattern."
  },
  {
    "name": "GdsDialog",
    "status": "registered",
    "home": {
      "id": "modals",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsDirectionBoundary",
    "status": "exempt",
    "reason": "Layout/RTL utility boundary — not a standalone catalog pattern."
  },
  {
    "name": "GdsDivergingBarChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsDrawer",
    "status": "exempt",
    "reason": "Overlay alias (OverlayManager) — same overlay pattern registered via FilterDrawer / GdsSidePanel on the drawers row."
  },
  {
    "name": "GdsEmptyStateTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsErrorPageTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsFormattedCurrency",
    "status": "exempt",
    "reason": "i18n formatter surface (GdsI18nRuntime) — value formatter, not a catalog pattern."
  },
  {
    "name": "GdsFormattedDate",
    "status": "exempt",
    "reason": "i18n formatter surface (GdsI18nRuntime) — value formatter."
  },
  {
    "name": "GdsFormattedNumber",
    "status": "exempt",
    "reason": "i18n formatter surface (GdsI18nRuntime) — value formatter."
  },
  {
    "name": "GdsFormProvider",
    "status": "exempt",
    "reason": "Provider/context (form orchestration) — non-visual; forms pattern is registered via useGdsForm."
  },
  {
    "name": "GdsGaugeChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsGeneratedAvatar",
    "status": "registered",
    "home": {
      "id": "generated-imagery",
      "family": "systems",
      "section": "Generated Imagery"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsGeneratedHero",
    "status": "registered",
    "home": {
      "id": "generated-imagery",
      "family": "systems",
      "section": "Generated Imagery"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsGeneratedMark",
    "status": "registered",
    "home": {
      "id": "generated-imagery",
      "family": "systems",
      "section": "Generated Imagery"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsGeneratedThumbnail",
    "status": "registered",
    "home": {
      "id": "generated-imagery",
      "family": "systems",
      "section": "Generated Imagery"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsGrid",
    "status": "exempt",
    "reason": "Layout primitive (grid) — composed into registered patterns."
  },
  {
    "name": "GdsGuidedTour",
    "status": "exempt",
    "reason": "Declarative controller (guided tour) — renders null and starts a tour via useGdsTour; non-visual, covered as support-api."
  },
  {
    "name": "GdsHistogramChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsIcon",
    "status": "exempt",
    "reason": "Icon surface (GDS-owned icon component) — icon rendering primitive, not a catalog pattern."
  },
  {
    "name": "GdsIcons",
    "status": "exempt",
    "reason": "Icon surface (GDS-owned icon registry) — icon set, not a catalog pattern."
  },
  {
    "name": "GdsInline",
    "status": "exempt",
    "reason": "Layout primitive (inline row) — composed into registered patterns."
  },
  {
    "name": "GdsInlineLink",
    "status": "exempt",
    "reason": "Inline text-link atom (governed Anchor) — composed into registered patterns and reference pages, not itself a catalog pattern; the typography-atom precedent."
  },
  {
    "name": "GdsLayoutTemplatePreview",
    "status": "exempt",
    "reason": "Catalog/preview component (LayoutTemplatePreview) — template preview host, not a catalog pattern."
  },
  {
    "name": "GdsLineChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsLocaleText",
    "status": "exempt",
    "reason": "i18n runtime surface (GdsI18nRuntime) — message resolver, not a catalog pattern."
  },
  {
    "name": "GdsLongitudinalChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsMapBasemapWash",
    "status": "registered",
    "home": {
      "id": "gds-map",
      "family": "public",
      "section": "Map System"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsMapFilterRail",
    "status": "registered",
    "home": {
      "id": "gds-map",
      "family": "public",
      "section": "Map System"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsMapPinBadge",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": [
      "badges"
    ]
  },
  {
    "name": "GdsMapPinPreviewCard",
    "status": "registered",
    "home": {
      "id": "gds-map",
      "family": "public",
      "section": "Map System"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsMaturityRadarChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsMediaFrame",
    "status": "exempt",
    "reason": "Layout primitive (aspect-ratio media frame) — composed into registered patterns."
  },
  {
    "name": "GdsModal",
    "status": "exempt",
    "reason": "Overlay alias (OverlayManager) — same overlay pattern registered via ConfirmDialog / GdsDialog on the modals row."
  },
  {
    "name": "GdsMotionSystemReference",
    "status": "registered",
    "home": {
      "id": "motion-system",
      "family": "foundations",
      "section": "Motion Tokens"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsNotificationCenter",
    "status": "registered",
    "home": {
      "id": "loaders-skeletons",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsNotificationProvider",
    "status": "registered",
    "home": {
      "id": "loaders-skeletons",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsOverflowFrame",
    "status": "exempt",
    "reason": "Layout primitive (overflow frame) — composed into registered patterns."
  },
  {
    "name": "GdsPageTemplateCatalog",
    "status": "exempt",
    "reason": "Catalog component (GdsPageTemplates) — template index, not a catalog pattern."
  },
  {
    "name": "GdsPinSystemReference",
    "status": "registered",
    "home": {
      "id": "pin-system",
      "family": "public",
      "section": "Map System"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsPlural",
    "status": "exempt",
    "reason": "i18n runtime surface (GdsI18nRuntime) — pluralization helper."
  },
  {
    "name": "GdsPublicEventTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsRadarChart",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsRatingScale",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsRelativeTime",
    "status": "exempt",
    "reason": "i18n formatter surface (GdsI18nRuntime) — relative-time formatter."
  },
  {
    "name": "GdsRemovableTag",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsResourceManager",
    "status": "exempt",
    "reason": "Client-runtime composite (GdsResourceManager.client) — CRUD manager scaffold, not a standalone catalog pattern."
  },
  {
    "name": "GdsResourceManagerTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsResponsiveChartFrame",
    "status": "exempt",
    "reason": "Chart frame primitive (GdsChart) — responsive frame, not a standalone pattern."
  },
  {
    "name": "GdsResponsiveVisibility",
    "status": "exempt",
    "reason": "Layout utility (responsive show/hide) — not a standalone catalog pattern."
  },
  {
    "name": "GdsSafeBox",
    "status": "exempt",
    "reason": "Layout primitive (safe-area box) — composed into registered patterns."
  },
  {
    "name": "GdsSavedIndicator",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSchemaForm",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSegmentedControl",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSettingsTemplate",
    "status": "exempt",
    "reason": "Page template (GdsPageTemplates) — full-page scaffold."
  },
  {
    "name": "GdsShapeElevationSystemReference",
    "status": "registered",
    "home": {
      "id": "shape-elevation",
      "family": "foundations",
      "section": "Shape & Elevation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSheet",
    "status": "exempt",
    "reason": "Overlay alias (OverlayManager) — bottom-sheet alias of the registered drawers overlay pattern."
  },
  {
    "name": "GdsSidebar",
    "status": "exempt",
    "reason": "Layout primitive (sidebar frame) — composed into registered shells."
  },
  {
    "name": "GdsSidePanel",
    "status": "registered",
    "home": {
      "id": "drawers",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSlider",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSlopeChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsSparkline",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsSplit",
    "status": "exempt",
    "reason": "Layout primitive (split) — composed into registered patterns."
  },
  {
    "name": "GdsStack",
    "status": "exempt",
    "reason": "Layout primitive (vertical stack) — composed into registered patterns."
  },
  {
    "name": "GdsStackedBarChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsSymmetryChart",
    "status": "exempt",
    "reason": "Chart wrapper (GdsChart) — variant of the registered reporting chart family."
  },
  {
    "name": "GdsTelemetryProvider",
    "status": "registered",
    "home": {
      "id": "alerts",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsToastProvider",
    "status": "exempt",
    "reason": "Provider/context (toast) — non-visual; notification pattern is registered via GdsNotificationProvider."
  },
  {
    "name": "GdsTourButton",
    "status": "exempt",
    "reason": "Thin guided-tour launcher affordance — a governed .gds-tour-launch button that calls useGdsTour().start(); demonstrated live on every site destination via SiteTourLauncher, covered as support-api (issue 475)."
  },
  {
    "name": "GdsTourProvider",
    "status": "exempt",
    "reason": "Provider/context (guided-tour runtime) — non-visual controller; renders the spotlight/step-card overlay imperatively via useGdsTour, covered as support-api."
  },
  {
    "name": "GdsValidationSummary",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsViewportFrame",
    "status": "registered",
    "home": {
      "id": "bottom-tab-navigation",
      "family": "public",
      "section": "Shell & Navigation Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "GdsVocabulary",
    "status": "exempt",
    "reason": "i18n/vocabulary runtime surface (vocabulary) — provider/consumer helper, not a catalog pattern."
  },
  {
    "name": "GdsWizardStepper",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "InfoCard",
    "status": "registered",
    "home": {
      "id": "info-card",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "InlineAlert",
    "status": "registered",
    "home": {
      "id": "alerts",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": [
      "loaders-skeletons"
    ]
  },
  {
    "name": "InlineEmphasis",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "InlineText",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "KanbanBoard",
    "status": "registered",
    "home": {
      "id": "kanban-board",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "KanbanCard",
    "status": "exempt",
    "reason": "Kanban sub-part (KanbanBoard.client) — card cell composed inside the registered KanbanBoard pattern."
  },
  {
    "name": "KanbanColumn",
    "status": "exempt",
    "reason": "Kanban sub-part (KanbanBoard.client) — column composed inside the registered KanbanBoard pattern."
  },
  {
    "name": "LabelTag",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "LabelText",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "LayeredSurfaceSlot",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — composition helper, not a catalog pattern."
  },
  {
    "name": "ListingCard",
    "status": "registered",
    "home": {
      "id": "listing-card",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ListingProvider",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ListItemSection",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — list row helper, not a catalog pattern."
  },
  {
    "name": "MapPanel",
    "status": "registered",
    "home": {
      "id": "embed-surfaces",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": [
      "map-panel"
    ]
  },
  {
    "name": "MeaningBadge",
    "status": "registered",
    "home": {
      "id": "meaning-badge",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MediaCard",
    "status": "registered",
    "home": {
      "id": "media-card",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MediaField",
    "status": "registered",
    "home": {
      "id": "media-fields",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MediaPreviewCard",
    "status": "exempt",
    "reason": "Media utility surface (MediaPreviewCard) — preview cell composed into registered media patterns."
  },
  {
    "name": "MediaWithFallback",
    "status": "registered",
    "home": {
      "id": "media-with-fallback",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MetadataText",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "MetricCard",
    "status": "registered",
    "home": {
      "id": "metric-cards",
      "family": "operations",
      "section": "Dashboard & Panel Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MissingDataPrompt",
    "status": "registered",
    "home": {
      "id": "state-blocks",
      "family": "feedback",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "MonospaceInputFrame",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — input framing helper, not a catalog pattern."
  },
  {
    "name": "NotificationCenter",
    "status": "registered",
    "home": {
      "id": "loaders-skeletons",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "NotificationCenterView",
    "status": "exempt",
    "reason": "Sub-part of the notifications pattern registered via GdsNotificationProvider / NotificationCenter."
  },
  {
    "name": "NumberStepper",
    "status": "registered",
    "home": {
      "id": "number-stepper",
      "family": "public",
      "section": "Forms & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "NumericCell",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — tabular numeric cell helper, not a catalog pattern."
  },
  {
    "name": "OverflowContainer",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — overflow helper, not a catalog pattern."
  },
  {
    "name": "OverlayManagerProvider",
    "status": "registered",
    "home": {
      "id": "modals",
      "family": "feedback",
      "section": "Overlays & Feedback"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PageHeader",
    "status": "registered",
    "home": {
      "id": "stable-shell",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PageTitle",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "PartnerAboutPageSections",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerAmenityBadgeGrid",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerContactBlock",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerDiscoveryFilters",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerDiscoveryFooter",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerDiscoveryHeader",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerDiscoveryShell",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerFaqList",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerListIndex",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerMapControls",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerMapListShell",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerMapPin",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerNewsletterCapture",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerNewsletterForm",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerParentTipPanel",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerPlaceDetailTemplate",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PartnerPlaceResultCard",
    "status": "exempt",
    "reason": "Partner sub-part of the registered PartnerDiscoveryShell pattern family."
  },
  {
    "name": "PartnerSubmissionEntry",
    "status": "registered",
    "home": {
      "id": "partner-discovery-system",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PeriodSelector",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PillBar",
    "status": "registered",
    "home": {
      "id": "buttons",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PlaceholderPanel",
    "status": "registered",
    "home": {
      "id": "placeholder-panels",
      "family": "feedback",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PlaybackControls",
    "status": "exempt",
    "reason": "Sub-part of the registered PlaybackSurface pattern — controls cluster."
  },
  {
    "name": "PlaybackOverlayControls",
    "status": "exempt",
    "reason": "Sub-part of the registered PlaybackSurface pattern — overlay controls cluster."
  },
  {
    "name": "PlaybackSurface",
    "status": "registered",
    "home": {
      "id": "playback-surface",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ProductCard",
    "status": "registered",
    "home": {
      "id": "icon-buttons",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ProgressCard",
    "status": "registered",
    "home": {
      "id": "metric-cards",
      "family": "operations",
      "section": "Dashboard & Panel Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ProviderIdentityButton",
    "status": "exempt",
    "reason": "Sub-part of the registered ProviderIdentityButtonGroup / SocialAuthButtons pattern — single identity button."
  },
  {
    "name": "ProviderIdentityButtonGroup",
    "status": "registered",
    "home": {
      "id": "provider-identity-buttons",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicAcceptStep",
    "status": "exempt",
    "reason": "Sub-part of PublicCaptureFlow — flow step."
  },
  {
    "name": "PublicBrandFooter",
    "status": "registered",
    "home": {
      "id": "public-brand-footer",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicCaptureFlow",
    "status": "exempt",
    "reason": "Public capture-flow host — orchestrates the Public*Step parts; flow is exercised via public shell patterns, not a standalone atom."
  },
  {
    "name": "PublicConsentStep",
    "status": "exempt",
    "reason": "Sub-part of PublicCaptureFlow — flow step."
  },
  {
    "name": "PublicCtaStep",
    "status": "exempt",
    "reason": "Sub-part of PublicCaptureFlow — flow step."
  },
  {
    "name": "PublicFlowShell",
    "status": "registered",
    "home": {
      "id": "public-flow-shell",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicFoodCard",
    "status": "registered",
    "home": {
      "id": "public-food-card",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicIdentityStep",
    "status": "exempt",
    "reason": "Sub-part of PublicCaptureFlow — flow step, not a standalone catalog pattern."
  },
  {
    "name": "PublicNav",
    "status": "registered",
    "home": {
      "id": "public-nav",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicProductCard",
    "status": "registered",
    "home": {
      "id": "public-product-cards",
      "family": "public",
      "section": "Discovery & Listing"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicRestartStep",
    "status": "exempt",
    "reason": "Sub-part of PublicCaptureFlow — flow step."
  },
  {
    "name": "PublicShareOverlay",
    "status": "exempt",
    "reason": "Sub-part of the public capture/share flow — overlay slot, not a standalone catalog pattern."
  },
  {
    "name": "PublicShell",
    "status": "registered",
    "home": {
      "id": "public-shells",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "PublicSiteFooter",
    "status": "registered",
    "home": {
      "id": "public-site-footer",
      "family": "public",
      "section": "Editorial & Brand Storytelling"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ReferenceLinkGrid",
    "status": "registered",
    "home": {
      "id": "reference-link-grid",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ReferenceLocaleNotice",
    "status": "registered",
    "home": {
      "id": "reference-locale-notice",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ReferenceSection",
    "status": "registered",
    "home": {
      "id": "reference-section",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ReferenceSiteShell",
    "status": "registered",
    "home": {
      "id": "reference-site-shell",
      "family": "public",
      "section": "Public Shells & Docs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ReportingSection",
    "status": "registered",
    "home": {
      "id": "reporting-contracts",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ResponsiveDataView",
    "status": "registered",
    "home": {
      "id": "responsive-data-view",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ResultSummary",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SearchableSelect",
    "status": "registered",
    "home": {
      "id": "searchable-select",
      "family": "public",
      "section": "Forms & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SectionPanel",
    "status": "registered",
    "home": {
      "id": "section-panels",
      "family": "operations",
      "section": "Dashboard & Panel Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SectionTitle",
    "status": "exempt",
    "reason": "Typography atom (Typography) — text primitive."
  },
  {
    "name": "SemanticButton",
    "status": "registered",
    "home": {
      "id": "semantic-actions",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SemanticChartFrame",
    "status": "exempt",
    "reason": "Chart frame primitive (SemanticCharts) — composition frame, not a standalone pattern."
  },
  {
    "name": "SemanticInset",
    "status": "exempt",
    "reason": "Style utility (StyleUtilities) — spacing helper, not a catalog pattern."
  },
  {
    "name": "SemanticNavLink",
    "status": "registered",
    "home": {
      "id": "semantic-nav-link",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ShareButtonGroup",
    "status": "registered",
    "home": {
      "id": "share-button-group",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SidebarNav",
    "status": "registered",
    "home": {
      "id": "sidebar-navigation",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SidebarNavItem",
    "status": "registered",
    "home": {
      "id": "sidebar-navigation",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SidebarNavSection",
    "status": "registered",
    "home": {
      "id": "sidebar-navigation",
      "family": "components",
      "section": "Shell & Navigation"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SimpleDataTable",
    "status": "registered",
    "home": {
      "id": "simple-data-tables",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SocialAuthButtons",
    "status": "registered",
    "home": {
      "id": "social-auth-buttons",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SoftChipGroup",
    "status": "registered",
    "home": {
      "id": "buttons",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "SortMenu",
    "status": "registered",
    "home": {
      "id": "data-toolbars",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "StateBlock",
    "status": "registered",
    "home": {
      "id": "state-blocks",
      "family": "feedback",
      "section": "State & Recovery Components"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "StatsSection",
    "status": "registered",
    "home": {
      "id": "stats-sections",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "StatsStrip",
    "status": "registered",
    "home": {
      "id": "stats-strip",
      "family": "data",
      "section": "Search & Data Views"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "StatusBadge",
    "status": "registered",
    "home": {
      "id": "badges",
      "family": "systems",
      "section": "Badges & Indicators"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "StreamingIndicator",
    "status": "registered",
    "home": {
      "id": "conversation-surface",
      "family": "public",
      "section": "Public Product Surfaces"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ThemeToggle",
    "status": "registered",
    "home": {
      "id": "theme-toggle",
      "family": "components",
      "section": "Controls & Inputs"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "UploadDropzone",
    "status": "registered",
    "home": {
      "id": "upload-surfaces",
      "family": "access",
      "section": "Auth, Share, & Access"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "ValidatedFieldMessage",
    "status": "registered",
    "home": {
      "id": "dashboards",
      "family": "operations",
      "section": "Workflow Guidance"
    },
    "alsoAppearsIn": []
  },
  {
    "name": "VisuallyHidden",
    "status": "exempt",
    "reason": "Accessibility utility (visually-hidden text) — not a visible catalog pattern."
  },
  {
    "name": "WorkspaceHeader",
    "status": "registered",
    "home": {
      "id": "workspace-header",
      "family": "operations",
      "section": "Editing & Content Ops"
    },
    "alsoAppearsIn": []
  }
];
