// Generated by scripts/generate-component-census.mjs. Do not edit by hand.
//
// The count the reference site quotes, produced by the same function
// verify-component-catalog-parity enforces against — so the page and the gate cannot disagree.
// Regenerate with `npm run tokens:component-census`; `--check` fails on drift.

/** Public UI components exported by the GDS packages. */
export const GDS_PUBLIC_COMPONENT_COUNT = 292;
