export type PatternCoverageStatus =
  | 'live-demo'
  | 'static-reference'
  | 'pending-primitive'
  | 'blocked';

export type PatternFamily =
  | 'foundations'
  | 'public'
  | 'operations'
  | 'data'
  | 'access'
  | 'feedback';

export interface PatternRegistryEntry {
  id: string;
  title: string;
  docSection: string;
  family: PatternFamily;
  section: string;
  route: string;
  anchor: string;
  coverageStatus: PatternCoverageStatus;
  summary: string;
  importPath?: string;
  sourceComponent?: string;
}

type RawPatternRegistryEntry = Omit<PatternRegistryEntry, 'route' | 'anchor'>;

const rawPatternRegistry: RawPatternRegistryEntry[] = [
  {
    id: 'stable-shell',
    title: 'Stable Shell',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Shell & Navigation Guidance',
    coverageStatus: 'live-demo',
    summary: 'Authenticated products need one stable structural shell with obvious location and destination rhythm.',
  },
  {
    id: 'primary-navigation',
    title: 'Primary Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Shell & Navigation Guidance',
    coverageStatus: 'live-demo',
    summary: 'Primary navigation must expose destinations, not actions, and maintain active-route signaling.',
  },
  {
    id: 'mobile-navigation',
    title: 'Mobile Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Shell & Navigation Guidance',
    coverageStatus: 'live-demo',
    summary: 'Primary destinations must stay reachable on mobile without forcing hidden-drawer-only usage.',
  },
  {
    id: 'page-headers',
    title: 'Page Headers',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Shell & Navigation Guidance',
    coverageStatus: 'live-demo',
    summary: 'Page headers answer where the user is, what the surface is for, and what comes next.',
    importPath: '@doneisbetter/gds-admin',
    sourceComponent: 'PageHeader',
  },
  {
    id: 'shell-contracts',
    title: 'Shell Contracts',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Shell & Navigation Guidance',
    coverageStatus: 'live-demo',
    summary: 'Each user area must converge on one shell contract rather than page-local layout rhythm.',
  },
  {
    id: 'discovery-shell',
    title: 'Discovery Shell',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Layout Contracts',
    coverageStatus: 'live-demo',
    summary: 'Canonical sidebar-first shell with header, sidebar, main region, mobile collapse, and sticky navigation behavior.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DiscoveryShell',
  },
  {
    id: 'sidebar-navigation',
    title: 'Sidebar Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'foundations',
    section: 'Layout Contracts',
    coverageStatus: 'live-demo',
    summary: 'Governed sidebar IA with section labels, active states, and mobile-aware row rhythm.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'SidebarNav',
  },
  {
    id: 'dashboards',
    title: 'Dashboards',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Dashboards prioritize next actions and urgent exceptions before broad analytics, especially on mobile.',
  },
  {
    id: 'forms',
    title: 'Forms',
    docSection: 'Common Workflows & Patterns',
    family: 'foundations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Forms should validate without punishing typing and must expose grouped fields and loading submit states.',
  },
  {
    id: 'admin-editor-flows',
    title: 'Admin & Editor Flows',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Operational editing surfaces favor dense, predictable information and explicit bulk-action consequences.',
  },
  {
    id: 'search-filters-lists',
    title: 'Search, Filters, & Lists',
    docSection: 'Common Workflows & Patterns',
    family: 'data',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Filters stay near the data they affect, active filters remain removable, and preserved filter state is a feature.',
  },
  {
    id: 'destructive-actions',
    title: 'Destructive Actions',
    docSection: 'Common Workflows & Patterns',
    family: 'feedback',
    section: 'State & Recovery Guidance',
    coverageStatus: 'live-demo',
    summary: 'High-impact destructive actions must remain visually distinct and require explicit confirmation.',
  },
  {
    id: 'pattern-service-reuse',
    title: 'Pattern Service Reuse',
    docSection: 'Common Workflows & Patterns',
    family: 'foundations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Repeated cards, tables, auth panels, and state blocks should be implemented through shared contracts, not page-local composition.',
  },
  {
    id: 'semantic-actions',
    title: 'Semantic Actions',
    docSection: 'Common Workflows & Patterns',
    family: 'foundations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Repeated CTA rows and action stacks must use governed semantic actions instead of local button-group wrappers.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ActionBar',
  },
  {
    id: 'detail-surfaces',
    title: 'Detail Surfaces',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Drawer and page detail experiences should converge on one governed detail shell contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DetailProfileShell',
  },
  {
    id: 'embed-surfaces',
    title: 'Embed Surfaces',
    docSection: 'Common Workflows & Patterns',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Third-party embeds and maps must render inside the sanctioned GDS containment surface.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'MapPanel',
  },
  {
    id: 'buttons',
    title: 'Buttons',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Primary, secondary, subtle, and danger button emphasis must stay consistent across products.',
  },
  {
    id: 'choice-chips',
    title: 'Choice Chips',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Lightweight filter and scope chips should use governed active state and shared token rhythm.',
  },
  {
    id: 'icon-buttons',
    title: 'Icon Buttons',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Icon-only actions must stay labeled, focus-visible, and size-consistent in clusters.',
  },
  {
    id: 'inputs',
    title: 'Inputs (Text/Search/Password)',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Inputs need visible labels, nearby error text, and explicit password reveal behavior where relevant.',
  },
  {
    id: 'selects-combobox',
    title: 'Selects / Combobox',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Static selects and searchable selection need governed labeling, loading, empty, and mobile ergonomics.',
  },
  {
    id: 'checkboxes-radios',
    title: 'Checkboxes / Radios',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Controls & Inputs',
    coverageStatus: 'live-demo',
    summary: 'Checkbox, radio, and switch semantics must remain distinct and predictable.',
  },
  {
    id: 'product-cards',
    title: 'Product Cards',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Cards & Metrics',
    coverageStatus: 'live-demo',
    summary: 'Structured product cards keep fixed slots for media, metadata, status, and the primary action.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ProductCard',
  },
  {
    id: 'public-product-cards',
    title: 'Public Product Cards',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Media-first public cards must retain price, availability, helper text, and one clear mobile action.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'MediaCard',
  },
  {
    id: 'accent-panels',
    title: 'Accent Panels',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Cards & Metrics',
    coverageStatus: 'live-demo',
    summary: 'Accent surfaces must stay readable across color schemes without raw background hacks.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'AccentPanel',
  },
  {
    id: 'metric-cards',
    title: 'Metric Cards',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    coverageStatus: 'live-demo',
    summary: 'Metric and progress cards expose value hierarchy, trend semantics, and mobile-safe prioritization.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'MetricCard / ProgressCard',
  },
  {
    id: 'data-toolbars',
    title: 'Data Toolbars',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    coverageStatus: 'live-demo',
    summary: 'Search, filter, sort, reset, and create affordances must stay in a predictable operational order.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DataToolbar',
  },
  {
    id: 'state-blocks',
    title: 'State Blocks',
    docSection: 'Core Component Contracts',
    family: 'feedback',
    section: 'State & Recovery Components',
    coverageStatus: 'live-demo',
    summary: 'Loading, empty, error, permission, disabled, and success states now include shared presentation modes for centered/fill bounded surfaces.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'StateBlock',
  },
  {
    id: 'action-bar',
    title: 'Action Bar',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Layout Contracts',
    coverageStatus: 'live-demo',
    summary: 'Priority-driven CTA orchestration belongs to the semantic ActionBar contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ActionBar',
  },
  {
    id: 'listing-card',
    title: 'Listing Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Unified discovery card for events, venues, communities, and similar public objects.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ListingCard',
  },
  {
    id: 'share-button-group',
    title: 'Share Button Group',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Sharing should use governed copy/native/channel actions instead of product-local wrappers.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ShareButtonGroup',
  },
  {
    id: 'public-food-card',
    title: 'Public Food Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Food/menu cards need governed freshness, pickup, scarcity, and bundle semantics.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PublicFoodCard',
  },
  {
    id: 'food-menu-section',
    title: 'Food Menu Section',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Grouped weekly menus and category-based food composition build on the canonical food-card contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'FoodMenuSection',
  },
  {
    id: 'map-panel',
    title: 'Map Panel',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Embeds and third-party maps must live inside sanctioned panel chrome with governed states.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'MapPanel',
  },
  {
    id: 'detail-profile-shell',
    title: 'Detail Profile Shell',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    coverageStatus: 'live-demo',
    summary: 'Canonical page and drawer detail composition with hero, sections, actions, and related content.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DetailProfileShell',
  },
  {
    id: 'public-flow-shell',
    title: 'Public Flow Shell',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Staged consent, review, share, and recovery experiences should use one public-flow shell contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PublicFlowShell',
  },
  {
    id: 'playback-surface',
    title: 'Playback Surface',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Timed-media and kiosk presentation needs governed playback framing and degraded/error states.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PlaybackSurface',
  },
  {
    id: 'public-shells',
    title: 'Public Shells',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Public marketing, docs, and discovery surfaces need one branded shell contract with mobile nav behavior.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PublicShell',
  },
  {
    id: 'public-nav',
    title: 'Public Nav',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Primary public navigation uses explicit nav items, active state, and semantic aria-current handling.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PublicNav',
  },
  {
    id: 'auth-shells',
    title: 'Auth Shells',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Auth entry surfaces must own title, helper/error placement, and canonical social-auth positioning.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'AuthShell',
  },
  {
    id: 'social-auth-buttons',
    title: 'Social Auth Buttons',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Provider-button clusters need governed wording, spacing, loading, and provider-brand treatment.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'SocialAuthButtons',
  },
  {
    id: 'provider-identity-buttons',
    title: 'Provider Identity Buttons',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Canonical provider-brand button and grouped provider-lane components for identity surfaces.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ProviderIdentityButtonGroup',
  },
  {
    id: 'article-shells',
    title: 'Article Shells',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Docs, legal, and editorial reading surfaces need governed width, meta, and side-rail behavior.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ArticleShell',
  },
  {
    id: 'docs-page-shell',
    title: 'Docs Page Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Docs surfaces may add breadcrumbs, next-step links, and code-treatment slots without redefining readability.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DocsPageShell',
  },
  {
    id: 'docs-shell',
    title: 'Docs Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Canonical docs/reference shell for full-width public documentation with governed sidebar and header contracts.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DocsShell',
  },
  {
    id: 'reference-section',
    title: 'Reference Section',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Canonical section framing for official docs/reference pages with governed title, summary, and action rhythm.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ReferenceSection',
  },
  {
    id: 'reference-link-grid',
    title: 'Reference Link Grid',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Canonical docs/reference grid for install, governance, and demo navigation without local card wrappers.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ReferenceLinkGrid',
  },
  {
    id: 'reference-locale-notice',
    title: 'Reference Locale Notice',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Canonical disclosure for partial locale coverage so public language support claims remain explicit and honest.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ReferenceLocaleNotice',
  },
  {
    id: 'reference-theme-explorer',
    title: 'Reference Theme Explorer',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Official interactive explorer for shipped theme lanes, color-scheme preview, and bounded brand-theme controls.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ReferenceThemeExplorer',
  },
  {
    id: 'reference-site-shell',
    title: 'Reference Site Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Canonical reference-site shell for public route grouping and website-level docs/demo structure framing.',
    importPath: '@doneisbetter/gds-admin',
    sourceComponent: 'ReferenceSiteShell',
  },
  {
    id: 'editorial-hero',
    title: 'Editorial Hero',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    coverageStatus: 'live-demo',
    summary: 'Split text/media public hero sections need one deterministic collapse and CTA hierarchy contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'EditorialHero',
  },
  {
    id: 'feature-band',
    title: 'Feature Band',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    coverageStatus: 'live-demo',
    summary: 'Trust, service, and value strips must use a shared multi-column public band contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'FeatureBand',
  },
  {
    id: 'browse-surface',
    title: 'Browse Surface',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    coverageStatus: 'live-demo',
    summary: 'Catalog/discovery pages use one governed result header, toolbar, filter, and scope rhythm.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'BrowseSurface',
  },
  {
    id: 'editorial-cards',
    title: 'Editorial Cards',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    coverageStatus: 'live-demo',
    summary: 'Guide, promo, collection, and discovery cards must share one canonical media/title/meta/CTA contract.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'EditorialCard',
  },
  {
    id: 'consumer-sections',
    title: 'Consumer Sections',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    coverageStatus: 'live-demo',
    summary: 'Consumer account and member-dashboard clusters use a shared section shell with governed action placement.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ConsumerSection',
  },
  {
    id: 'consumer-dashboard-grid',
    title: 'Consumer Dashboard Grid',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    coverageStatus: 'live-demo',
    summary: 'Metric, progress, and account-summary cards should sit inside a shared responsive dashboard grid.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'ConsumerDashboardGrid',
  },
  {
    id: 'media-fields',
    title: 'Media Fields',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    coverageStatus: 'live-demo',
    summary: 'Media editing should unify upload, URL entry, preview, status, reset/remove, and policy messaging.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'MediaField',
  },
  {
    id: 'content-operations-editor',
    title: 'Content Operations Editor',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    coverageStatus: 'live-demo',
    summary: 'Admin settings and content editors need one scaffold for grouped editing, preview rails, and save bars.',
    importPath: '@doneisbetter/gds-admin',
    sourceComponent: 'ContentOpsEditor',
  },
  {
    id: 'section-panels',
    title: 'Section Panels',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    coverageStatus: 'live-demo',
    summary: 'Operational panels and detail sections now expose shared panel-body presentation controls (`inline`, `centered`, `fill`) so local wrappers are unnecessary.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'SectionPanel',
  },
  {
    id: 'public-brand-footer',
    title: 'Public Brand Footer',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    coverageStatus: 'live-demo',
    summary: 'Narrative and media-driven public footers need a shared layout contract instead of repo-local footer systems.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PublicBrandFooter',
  },
  {
    id: 'filter-drawer',
    title: 'Filter Drawer',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'State & Recovery Components',
    coverageStatus: 'live-demo',
    summary: 'Mobile and operational filters must use a shared drawer or bottom-sheet contract with clear apply/reset behavior.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'FilterDrawer',
  },
  {
    id: 'docs-code-blocks',
    title: 'Docs Code Blocks',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    coverageStatus: 'live-demo',
    summary: 'Install and reference code blocks need a shared wrapper with accessible copy affordances.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'DocsCodeBlock',
  },
  {
    id: 'cta-button-groups',
    title: 'CTA Button Groups',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    coverageStatus: 'live-demo',
    summary: 'Public CTA groups must preserve one obvious primary action and stack safely on smaller screens.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'CtaButtonGroup',
  },
  {
    id: 'upload-surfaces',
    title: 'Upload Surfaces',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Upload and drop surfaces need explicit drag state, error, replace, remove, and a11y labeling behavior.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'UploadDropzone',
  },
  {
    id: 'access-summaries',
    title: 'Access Summaries',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    coverageStatus: 'live-demo',
    summary: 'Role, scope, blocked, and ownership cues must remain explicit and not rely on color only.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'AccessSummary',
  },
  {
    id: 'access-recovery-panels',
    title: 'Access Recovery Panels',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'State & Recovery Components',
    coverageStatus: 'live-demo',
    summary: 'Protected-content and expired-session failures need one canonical recovery surface with clear next actions.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'AccessRecoveryPanel',
  },
  {
    id: 'placeholder-panels',
    title: 'Placeholder Panels',
    docSection: 'Core Component Contracts',
    family: 'feedback',
    section: 'State & Recovery Components',
    coverageStatus: 'live-demo',
    summary: 'Placeholder and coming-soon surfaces must stay honest, visibly non-live, and free of fabricated data.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'PlaceholderPanel',
  },
  {
    id: 'simple-data-tables',
    title: 'Simple Data Tables',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    coverageStatus: 'live-demo',
    summary: 'Public and product summary tables need governed loading, empty, error, and threshold-safe states.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'SimpleDataTable',
  },
  {
    id: 'stats-sections',
    title: 'Stats Sections',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    coverageStatus: 'live-demo',
    summary: 'Lightweight reporting sections need explicit loading, threshold, error, and live states.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'StatsSection',
  },
  {
    id: 'alerts',
    title: 'Alerts',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Alerts must explain the current state and the next action instead of acting as decorative chrome.',
  },
  {
    id: 'loaders-skeletons',
    title: 'Loaders & Skeletons',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Skeletons belong to known layouts, while loaders belong to actions and longer operations need explicit text status.',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Notifications are transient cross-surface feedback and may not be the only place a critical error appears.',
  },
  {
    id: 'badges',
    title: 'Badges',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Badges are compact state cues and must not rely on color only.',
  },
  {
    id: 'modals',
    title: 'Modals',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Modals support focused edits and confirmations with trapped focus and no stacking.',
  },
  {
    id: 'drawers',
    title: 'Drawers',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Messaging Primitives',
    coverageStatus: 'live-demo',
    summary: 'Drawers support filters and secondary panels with explicit mobile and desktop sizing behavior.',
  },
  {
    id: 'small-screen-priority',
    title: 'Small-Screen Priority',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'feedback',
    section: 'Responsive Guidance',
    coverageStatus: 'live-demo',
    summary: 'On small screens the system prioritizes next actions, urgent exceptions, recent work, then analytics.',
  },
  {
    id: 'table-responsive-strategies',
    title: 'Table Responsive Strategies',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'data',
    section: 'Responsive Guidance',
    coverageStatus: 'live-demo',
    summary: 'Desktop tables must adapt through scroll, cards, priority columns, or stacked rows rather than naive shrinking.',
  },
  {
    id: 'mobile-action-density',
    title: 'Mobile Action Density',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'feedback',
    section: 'Responsive Guidance',
    coverageStatus: 'live-demo',
    summary: 'Cards should keep one visible primary action on mobile and avoid risky icon-only adjacency.',
  },
  {
    id: 'searchable-selection',
    title: 'Searchable Selection',
    docSection: 'Required Reusable Pattern Families',
    family: 'data',
    section: 'Search & Data Views',
    coverageStatus: 'live-demo',
    summary: 'Searchable selection follows the documented Mantine recipe path until a dedicated GDS export is promoted.',
  },
  {
    id: 'vocabulary-extension-lane',
    title: 'Semantic Vocabulary Extension Lane',
    docSection: 'Semantic Vocabulary Extension Lane',
    family: 'foundations',
    section: 'Workflow Guidance',
    coverageStatus: 'live-demo',
    summary: 'Products may extend semantic action vocabulary through governed namespaced packs rather than raw labels.',
    importPath: '@doneisbetter/gds-core',
    sourceComponent: 'createGdsVocabularyPack',
  },
];

export const patternRegistry: PatternRegistryEntry[] = rawPatternRegistry.map((entry) => ({
  ...entry,
  route: `/patterns/${entry.family}`,
  anchor: entry.id,
}));

export const documentedPatternIds = patternRegistry.map((entry) => entry.id);

export function getFamilyEntries(family: PatternFamily) {
  return patternRegistry.filter((entry) => entry.family === family);
}
