export type ExportCoveragePackage = '@doneisbetter/gds-core' | '@doneisbetter/gds-admin';

export type ExportCoverageStatus = 'live-demo' | 'support-api' | 'compatibility';

export interface ExportCoverageEntry {
  exportName: string;
  packageName: ExportCoveragePackage;
  status: ExportCoverageStatus;
  registryId: string;
  rationale: string;
}

export const patternExportCoverage: ExportCoverageEntry[] = [
  { packageName: '@doneisbetter/gds-core', exportName: 'AccessRecoveryPanel', status: 'live-demo', registryId: 'access-recovery-panels', rationale: 'Canonical protected-content recovery surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'AccessSummary', status: 'live-demo', registryId: 'access-summaries', rationale: 'Canonical scoped access and role summary.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'AccentPanel', status: 'live-demo', registryId: 'accent-panels', rationale: 'Canonical color-mode-safe accent surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ActionBar', status: 'live-demo', registryId: 'action-bar', rationale: 'Canonical semantic action orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'AdvancedDataTable', status: 'live-demo', registryId: 'admin-data-table', rationale: 'Canonical advanced table contract with sort, selection, density, sticky header, and fallback cards.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ArticleShell', status: 'live-demo', registryId: 'article-shells', rationale: 'Canonical docs/editorial readability shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'AuthShell', status: 'live-demo', registryId: 'auth-shells', rationale: 'Canonical auth entry composition.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'AsyncSurface', status: 'live-demo', registryId: 'state-blocks', rationale: 'Canonical async loading/empty/error/retry surface orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'BrowseSurface', status: 'live-demo', registryId: 'browse-surface', rationale: 'Canonical browse/search/list surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ChartTokenPanel', status: 'live-demo', registryId: 'reporting-contracts', rationale: 'Canonical chart-token and accessible chart fallback wrapper.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsChart', status: 'live-demo', registryId: 'reporting-contracts', rationale: 'Governed multi-type chart primitive with shared state and fallback semantics.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsChartTypeRegistry', status: 'support-api', registryId: 'reporting-contracts', rationale: 'Canonical chart type registry for governed chart lanes and rendering budgets.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsChartSetATypeRegistry', status: 'support-api', registryId: 'reporting-contracts', rationale: 'Governed Set A chart registry for line, area, bar, stacked-bar, pie, donut, radar, and scatter primitives.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'isGdsChartSetAType', status: 'support-api', registryId: 'reporting-contracts', rationale: 'Type guard for Set A chart primitives and follow-up chart sequencing.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsDefaultChartLegend', status: 'support-api', registryId: 'reporting-contracts', rationale: 'Default non-color-only token legend for chart primitives.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'validateGdsChartData', status: 'support-api', registryId: 'reporting-contracts', rationale: 'Runtime chart dataset validation for empty, threshold, schema, and budget states.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ChoiceChip', status: 'live-demo', registryId: 'choice-chips', rationale: 'Canonical lightweight choice/filter chip.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ConfirmDialog', status: 'live-demo', registryId: 'modals', rationale: 'Canonical confirmation modal contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ConsumerDashboardGrid', status: 'live-demo', registryId: 'consumer-dashboard-grid', rationale: 'Canonical consumer dashboard grid.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ConsumerSection', status: 'live-demo', registryId: 'consumer-sections', rationale: 'Canonical consumer/member section surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'CtaButtonGroup', status: 'live-demo', registryId: 'cta-button-groups', rationale: 'Canonical public CTA grouping contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DataToolbar', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical data-toolbar action rhythm.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ListingProvider', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical listing provider for shared query/filter/sort/selection state.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useListingState', status: 'support-api', registryId: 'data-toolbars', rationale: 'Listing query-state hook backing toolbar, filters, sorting, and selection.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'listingQueryReducer', status: 'support-api', registryId: 'data-toolbars', rationale: 'Deterministic listing query-state reducer for consumer testing and orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ActiveFilterChips', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical active-filter chips with removable filter affordance.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ResultSummary', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical result-count and listing-scope summary surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SortMenu', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical sort selection control with typed options.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'BulkActionsBar', status: 'live-demo', registryId: 'data-toolbars', rationale: 'Canonical selected-row bulk actions surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DetailProfileShell', status: 'live-demo', registryId: 'detail-profile-shell', rationale: 'Canonical detail/profile page and drawer shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DiscoveryShell', status: 'live-demo', registryId: 'discovery-shell', rationale: 'Canonical sidebar-first app shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DocsCodeBlock', status: 'live-demo', registryId: 'docs-code-blocks', rationale: 'Canonical install/docs code block.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DocsPageShell', status: 'live-demo', registryId: 'docs-page-shell', rationale: 'Canonical docs article page shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'DocsShell', status: 'live-demo', registryId: 'docs-shell', rationale: 'Canonical full-width docs/reference shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'EditorialCard', status: 'live-demo', registryId: 'editorial-cards', rationale: 'Canonical editorial card contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'EditorialHero', status: 'live-demo', registryId: 'editorial-hero', rationale: 'Canonical split editorial hero.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'EmptyState', status: 'live-demo', registryId: 'empty-state', rationale: 'Compatibility state primitive represented in the feedback family.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'EvidencePanel', status: 'live-demo', registryId: 'reporting-contracts', rationale: 'Canonical evidence/source/freshness reporting panel.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'FeatureBand', status: 'live-demo', registryId: 'feature-band', rationale: 'Canonical public feature/value band.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'FilterDrawer', status: 'live-demo', registryId: 'filter-drawer', rationale: 'Canonical filter drawer/bottom-sheet contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'FoodMenuSection', status: 'live-demo', registryId: 'food-menu-section', rationale: 'Canonical grouped food/menu section.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'FormField', status: 'live-demo', registryId: 'form-field', rationale: 'Canonical label, description, error, and control wrapper.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useGdsForm', status: 'support-api', registryId: 'forms', rationale: 'Canonical form controller hook for touched/dirty/validation/submit orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsFormReducer', status: 'support-api', registryId: 'forms', rationale: 'Deterministic form reducer for controlled field/validation/submit transitions.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsFormProvider', status: 'support-api', registryId: 'forms', rationale: 'Form snapshot context provider used by validation-summary primitives.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useGdsFormSnapshot', status: 'support-api', registryId: 'forms', rationale: 'Snapshot hook for governed field-level validation projections.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'FormErrorSummary', status: 'live-demo', registryId: 'forms', rationale: 'Canonical blocking validation summary with jump targets.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ValidatedFieldMessage', status: 'support-api', registryId: 'forms', rationale: 'Canonical field-level validation message projection from the governed form state.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'OverlayManagerProvider', status: 'support-api', registryId: 'modals', rationale: 'Overlay stack runtime for deterministic top-most close and focus-return behavior.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useOverlayManager', status: 'support-api', registryId: 'drawers', rationale: 'Overlay-manager hook for nested overlay orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'CommandRegistryProvider', status: 'live-demo', registryId: 'drawers', rationale: 'Keyboard-first command registry and quick-action palette runtime.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'CommandPalette', status: 'support-api', registryId: 'drawers', rationale: 'Modal quick-action surface with keyboard-first search and execution.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useCommandLauncher', status: 'support-api', registryId: 'drawers', rationale: 'Launcher hook for opening the command palette and registering commands.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsTelemetryProvider', status: 'support-api', registryId: 'alerts', rationale: 'Cross-primitive telemetry provider with sampling and privacy-safe context redaction.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useGdsTelemetry', status: 'support-api', registryId: 'alerts', rationale: 'Telemetry emit hook for standardized UI event contracts.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GameBoardTile', status: 'live-demo', registryId: 'game-board-tile', rationale: 'Bounded immersive/game tile primitive kept explicit in the catalog.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsIcons', status: 'support-api', registryId: 'icon-buttons', rationale: 'Icon registry supports governed visual actions rather than standalone page surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsVocabulary', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Core vocabulary registry is represented by semantic action demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ListingCard', status: 'live-demo', registryId: 'listing-card', rationale: 'Canonical public listing card.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsCardSize', status: 'support-api', registryId: 'product-cards', rationale: 'Shared card size contract for canonical card families.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsCardDensity', status: 'support-api', registryId: 'product-cards', rationale: 'Shared compact/comfortable/spacious density contract for canonical card families.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsCardVariant', status: 'support-api', registryId: 'product-cards', rationale: 'Shared card layout variant contract for default, media-top, media-left, and compact presentation.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsCardInteractiveMode', status: 'support-api', registryId: 'listing-card', rationale: 'Shared interactive card mode vocabulary for surface/button/flip behavior.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'resolveGdsCardContract', status: 'support-api', registryId: 'product-cards', rationale: 'Deterministic resolver for card size, density, variant, title, spacing, and verification attributes.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsCardSizePaddingMap', status: 'support-api', registryId: 'product-cards', rationale: 'Deterministic card size-to-padding token map for governed card families.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsCardDensityPaddingMap', status: 'support-api', registryId: 'product-cards', rationale: 'Density-aware card padding matrix used by the shared card contract resolver.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsCardGapMap', status: 'support-api', registryId: 'product-cards', rationale: 'Density-to-spacing token map used by governed card families.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsCardMediaRatioMap', status: 'support-api', registryId: 'product-cards', rationale: 'Variant-to-media-ratio map used by governed media-first card families.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'gdsCardTitleOrderMap', status: 'support-api', registryId: 'product-cards', rationale: 'Deterministic card size-to-title hierarchy map.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'MapPanel', status: 'live-demo', registryId: 'map-panel', rationale: 'Canonical map/embed containment surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'MediaCard', status: 'live-demo', registryId: 'media-card', rationale: 'Compatibility media card represented separately from PublicProductCard.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'MediaField', status: 'live-demo', registryId: 'media-fields', rationale: 'Canonical media selection/editing field.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'MetricCard', status: 'live-demo', registryId: 'metric-cards', rationale: 'Canonical metric card.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'GdsNotificationProvider', status: 'live-demo', registryId: 'notifications', rationale: 'Canonical notification provider and queue contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'NotificationCenter', status: 'live-demo', registryId: 'notifications', rationale: 'Canonical persistent notification-center rendering contract.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'NotificationCenterView', status: 'support-api', registryId: 'notifications', rationale: 'Server-safe notification-center view used by the client queue facade.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'InlineAlert', status: 'live-demo', registryId: 'alerts', rationale: 'Canonical inline alert primitive for local contextual messaging.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'BannerNotice', status: 'live-demo', registryId: 'notifications', rationale: 'Canonical banner-style notification surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PageHeader', status: 'live-demo', registryId: 'page-headers', rationale: 'Core page-header contract for public/shared surfaces.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PeriodSelector', status: 'live-demo', registryId: 'reporting-contracts', rationale: 'Canonical period/scope selector for reporting surfaces.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PlaceholderPanel', status: 'live-demo', registryId: 'placeholder-panels', rationale: 'Canonical honest placeholder/coming-soon surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PlaybackSurface', status: 'live-demo', registryId: 'playback-surface', rationale: 'Canonical playback/kiosk/media frame.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ProductCard', status: 'live-demo', registryId: 'product-cards', rationale: 'Canonical product card.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ProgressCard', status: 'live-demo', registryId: 'metric-cards', rationale: 'Progress card is covered with metric-card family demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ProviderIdentityButton', status: 'live-demo', registryId: 'provider-identity-buttons', rationale: 'Canonical provider-branded identity button.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ProviderIdentityButtonGroup', status: 'live-demo', registryId: 'provider-identity-buttons', rationale: 'Canonical provider-branded identity button group.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicBrandFooter', status: 'live-demo', registryId: 'public-brand-footer', rationale: 'Canonical narrative public footer.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicFlowShell', status: 'live-demo', registryId: 'public-flow-shell', rationale: 'Canonical staged public flow shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicFoodCard', status: 'live-demo', registryId: 'public-food-card', rationale: 'Canonical food/menu listing card.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicNav', status: 'live-demo', registryId: 'public-nav', rationale: 'Canonical public navigation row.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicProductCard', status: 'live-demo', registryId: 'public-product-cards', rationale: 'Canonical media-first public product card.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicShell', status: 'live-demo', registryId: 'public-shells', rationale: 'Canonical public shell.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'PublicSiteFooter', status: 'live-demo', registryId: 'public-site-footer', rationale: 'Simple public footer primitive retained as explicit coverage.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ReferenceLinkGrid', status: 'live-demo', registryId: 'reference-link-grid', rationale: 'Canonical reference link grid.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ReferenceLocaleNotice', status: 'live-demo', registryId: 'reference-locale-notice', rationale: 'Canonical locale coverage disclosure.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ReferenceSection', status: 'live-demo', registryId: 'reference-section', rationale: 'Canonical reference section.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ReferenceThemeExplorer', status: 'live-demo', registryId: 'reference-theme-explorer', rationale: 'Canonical theme explorer.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ReportingSection', status: 'live-demo', registryId: 'reporting-contracts', rationale: 'Canonical reporting composition for metrics, evidence, chart, and period controls.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SectionPanel', status: 'live-demo', registryId: 'section-panels', rationale: 'Canonical section/panel surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SemanticButton', status: 'live-demo', registryId: 'semantic-actions', rationale: 'Semantic button covered by semantic actions and CTA demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ShareButtonGroup', status: 'live-demo', registryId: 'share-button-group', rationale: 'Canonical public share surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SidebarNav', status: 'live-demo', registryId: 'sidebar-navigation', rationale: 'Canonical sidebar navigation group.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SidebarNavItem', status: 'live-demo', registryId: 'sidebar-navigation', rationale: 'Canonical sidebar navigation item.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SidebarNavSection', status: 'live-demo', registryId: 'sidebar-navigation', rationale: 'Canonical sidebar navigation section.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SimpleDataTable', status: 'live-demo', registryId: 'simple-data-tables', rationale: 'Canonical simple public/product table.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SocialAuthButtons', status: 'compatibility', registryId: 'social-auth-buttons', rationale: 'Compatibility facade; preferred lane is ProviderIdentityButtonGroup.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'StateBlock', status: 'live-demo', registryId: 'state-blocks', rationale: 'Canonical state surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'StatsSection', status: 'live-demo', registryId: 'stats-sections', rationale: 'Canonical lightweight stats/reporting section.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'StatusBadge', status: 'live-demo', registryId: 'badges', rationale: 'Canonical status badge.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'CountBadge', status: 'live-demo', registryId: 'badges', rationale: 'Canonical numeric count badge with capped-overflow semantics.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'LabelTag', status: 'live-demo', registryId: 'badges', rationale: 'Canonical taxonomy label tag with governed tones.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'SurfacePresentation', status: 'support-api', registryId: 'surface-presentation', rationale: 'Shared presentation helper covered by StateBlock and SectionPanel demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'ThemeToggle', status: 'live-demo', registryId: 'theme-toggle', rationale: 'Canonical color-scheme toggle control.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'UploadDropzone', status: 'live-demo', registryId: 'upload-surfaces', rationale: 'Canonical upload/drop surface.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useDiscoveryShellState', status: 'support-api', registryId: 'discovery-shell', rationale: 'Shell-state governance hook for canonical DiscoveryShell open/collapse behavior.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'useGdsNotifications', status: 'support-api', registryId: 'notifications', rationale: 'Notification queue hook for notify/dismiss/clear orchestration.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'createGdsVocabularyPack', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Vocabulary pack helper supports semantic action extension.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getGdsMessages', status: 'support-api', registryId: 'reference-locale-notice', rationale: 'Locale helper supports localized vocabulary and honest locale coverage.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getProviderIdentityLabel', status: 'support-api', registryId: 'provider-identity-buttons', rationale: 'Provider-label helper supports governed identity button demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getProviderIdentityPolicy', status: 'support-api', registryId: 'provider-identity-buttons', rationale: 'Provider policy helper supports identity-brand governance and audit logs.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getSemanticActionConfig', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Semantic vocabulary helper covered by action demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getSemanticActionLabel', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Server-safe semantic label helper covered by action demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getSupportedProviderIdentityIds', status: 'support-api', registryId: 'provider-identity-buttons', rationale: 'Supported provider list helper is represented by provider identity demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'mergeGdsVocabularyPacks', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Vocabulary composition helper covered by action demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'resolveAccentPanelStyles', status: 'support-api', registryId: 'accent-panels', rationale: 'Style helper is represented by AccentPanel demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'resolveSemanticActionConfig', status: 'support-api', registryId: 'vocabulary-extension-lane', rationale: 'Semantic vocabulary resolver covered by action demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'resolveSurfacePresentationStyles', status: 'support-api', registryId: 'surface-presentation', rationale: 'Presentation helper covered by SectionPanel and StateBlock demos.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'renderGdsLayout', status: 'live-demo', registryId: 'shell-contracts', rationale: 'Block-based governed layout renderer for schema-composed page assembly.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'renderGdsLayoutWithDiagnostics', status: 'support-api', registryId: 'shell-contracts', rationale: 'Schema renderer result with validation diagnostics for block-based page assembly.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'validateGdsLayout', status: 'support-api', registryId: 'shell-contracts', rationale: 'Layout schema validation for unsupported blocks, malformed props, and unsafe string content.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'registerGdsBlock', status: 'support-api', registryId: 'shell-contracts', rationale: 'Governed block registry extension lane for reusable product-authored blocks.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'getGdsBlockTypes', status: 'support-api', registryId: 'shell-contracts', rationale: 'Default and registered block type discovery for docs and adoption tooling.' },
  { packageName: '@doneisbetter/gds-core', exportName: 'isPresentationMode', status: 'support-api', registryId: 'surface-presentation', rationale: 'Presentation guard covered by SectionPanel and StateBlock demos.' },

  { packageName: '@doneisbetter/gds-admin', exportName: 'AppShell', status: 'live-demo', registryId: 'admin-app-shell', rationale: 'Admin compatibility shell built on DiscoveryShell.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'ContentOpsActionBar', status: 'live-demo', registryId: 'content-operations-editor', rationale: 'Content-ops action bar covered by editor demos.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'ContentOpsEditor', status: 'live-demo', registryId: 'content-operations-editor', rationale: 'Canonical content operations editor.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'ContentOpsSection', status: 'live-demo', registryId: 'content-operations-editor', rationale: 'Content-ops section covered by editor demos.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'DataTable', status: 'live-demo', registryId: 'admin-data-table', rationale: 'Admin table covered separately from public SimpleDataTable.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'EditorScaffold', status: 'live-demo', registryId: 'editor-scaffold', rationale: 'Canonical editor scaffold retained as explicit admin coverage.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'FormSection', status: 'live-demo', registryId: 'form-section', rationale: 'Admin form grouping primitive.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'InfoCard', status: 'live-demo', registryId: 'info-card', rationale: 'Admin information card primitive.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'PageHeader', status: 'live-demo', registryId: 'page-headers', rationale: 'Admin page-header contract.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'ReferenceSiteShell', status: 'compatibility', registryId: 'reference-site-shell', rationale: 'Compatibility reference shell retained while DocsShell is preferred.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'ResponsiveDataView', status: 'live-demo', registryId: 'responsive-data-view', rationale: 'Canonical admin responsive data view.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'SemanticNavLink', status: 'live-demo', registryId: 'semantic-nav-link', rationale: 'Admin semantic navigation link.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'StatsStrip', status: 'live-demo', registryId: 'stats-strip', rationale: 'Admin KPI strip primitive.' },
  { packageName: '@doneisbetter/gds-admin', exportName: 'WorkspaceHeader', status: 'live-demo', registryId: 'workspace-header', rationale: 'Admin workspace context header.' },
];
