import { provenPatternIds } from './generated-pattern-coverage.ts';

/** Derived, not authored — see the mapping at the bottom of this file. */
export type PatternCoverageStatus = 'live-proof' | 'static-reference';

export type PatternFamily =
  | 'foundations'
  | 'components'
  | 'systems'
  | 'public'
  | 'operations'
  | 'data'
  | 'access'
  | 'feedback';

export interface PatternRegistryEntry {
  id: string;
  title: string;
  docSection: string;
  family: PatternFamily;
  section: string;
  route: string;
  anchor: string;
  coverageStatus: PatternCoverageStatus;
  summary: string;
  importPath?: string;
  sourceComponent?: string;
}

// coverageStatus is derived below, not authored, so an entry can't claim a proof it lacks.
type RawPatternRegistryEntry = Omit<PatternRegistryEntry, 'route' | 'anchor' | 'coverageStatus'>;

const rawPatternRegistry: RawPatternRegistryEntry[] = [
  {
    id: 'stable-shell',
    title: 'Stable Shell',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Authenticated products need one stable structural shell with obvious location and destination rhythm.',
  },
  {
    id: 'primary-navigation',
    title: 'Primary Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Primary navigation must expose destinations, not actions, and maintain active-route signaling.',
  },
  {
    id: 'mobile-navigation',
    title: 'Mobile Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Primary destinations must stay reachable on mobile without forcing hidden-drawer-only usage.',
  },
  {
    id: 'page-headers',
    title: 'Page Headers',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Page headers answer where the user is, what the surface is for, and what comes next.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'PageHeader',
  },
  {
    id: 'theme-toggle',
    title: 'Theme Toggle',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Canonical color-scheme toggle for surfaces that need explicit user-controlled light/dark switching.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ThemeToggle',
  },
  {
    id: 'form-field',
    title: 'Form Field',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Canonical field wrapper for visible labels, descriptions, errors, and grouped control semantics.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FormField',
  },
  {
    id: 'game-board-tile',
    title: 'Game Board Tile',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Bounded immersive/game tile primitive with reduced-motion-aware reveal and matched states.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GameBoardTile',
  },
  {
    id: 'shell-contracts',
    title: 'Shell Contracts',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Each user area must converge on one shell contract rather than page-local layout rhythm.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DiscoveryShell / DocsShell / renderGdsLayout',
  },
  {
    id: 'discovery-shell',
    title: 'Discovery Shell',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Canonical sidebar-first shell with header, sidebar, main region, mobile collapse, and sticky navigation behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DiscoveryShell / AppShell',
  },
  {
    id: 'sidebar-navigation',
    title: 'Sidebar Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Governed sidebar IA with section labels, active states, and mobile-aware row rhythm.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'SidebarNav / SidebarNavSection / SidebarNavItem',
  },
  {
    id: 'dashboards',
    title: 'Dashboards',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Dashboards prioritize next actions and urgent exceptions before broad analytics, especially on mobile.',
  },
  {
    id: 'forms',
    title: 'Forms',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Forms should validate without punishing typing and must expose grouped fields and loading submit states. Includes a live GdsSchemaForm exercising the themed checkbox-group and repeatable field types.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'useGdsForm / useGdsFormOrchestration / GdsValidationSummary / FormErrorSummary / ValidatedFieldMessage / GdsSegmentedControl / GdsSlider / GdsRatingScale / GdsWizardStepper / GdsDateInput / GdsDateTimeInput / GdsDateRangeInput / GdsSchemaForm',
  },
  {
    id: 'admin-editor-flows',
    title: 'Admin & Editor Flows',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Operational editing surfaces favor dense, predictable information and explicit bulk-action consequences.',
  },
  {
    id: 'search-filters-lists',
    title: 'Search, Filters, & Lists',
    docSection: 'Common Workflows & Patterns',
    family: 'data',
    section: 'Workflow Guidance',
    summary: 'Filters stay near the data they affect, active filters remain removable, and preserved filter state is a feature.',
  },
  {
    id: 'destructive-actions',
    title: 'Destructive Actions',
    docSection: 'Common Workflows & Patterns',
    family: 'feedback',
    section: 'State & Recovery Guidance',
    summary: 'High-impact destructive actions must remain visually distinct and require explicit confirmation.',
  },
  {
    id: 'pattern-service-reuse',
    title: 'Pattern Service Reuse',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Repeated cards, tables, auth panels, and state blocks should be implemented through shared contracts, not page-local composition.',
  },
  {
    id: 'maturity-capabilities',
    title: 'Maturity Capabilities',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Issue-backed product maturity registry for the seven highest-value GDS capability groups, including contracts, accessibility, observability, rollback, testing, and documentation evidence.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'getGdsRecommendedMaturityCapabilities / getGdsMaturitySummary',
  },
  {
    id: 'semantic-actions',
    title: 'Semantic Actions',
    docSection: 'Common Workflows & Patterns',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Repeated CTA rows and action stacks must use governed semantic actions instead of local button-group wrappers. Each action button carries its own micro-interaction feedback — an icon, color, and message shown on click.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ActionBar / SemanticButton / createGdsVocabularyPack',
  },
  {
    id: 'detail-surfaces',
    title: 'Detail Surfaces',
    docSection: 'Common Workflows & Patterns',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Drawer and page detail experiences should converge on one governed detail shell contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DetailProfileShell',
  },
  {
    id: 'embed-surfaces',
    title: 'Embed Surfaces',
    docSection: 'Common Workflows & Patterns',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Third-party embeds and maps must render inside the sanctioned GDS containment surface.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MapPanel',
  },
  {
    id: 'buttons',
    title: 'Buttons',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Primary, secondary, subtle, and danger button emphasis must stay consistent across products.',
  },
  {
    id: 'choice-chips',
    title: 'Choice Chips',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Lightweight filter and scope chips should use governed active state and shared token rhythm.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ChoiceChip / PillBar / SoftChipGroup / FilterChipGroup',
  },
  {
    id: 'icon-buttons',
    title: 'Icon Buttons',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Icon-only actions must stay labeled, focus-visible, and size-consistent in clusters.',
  },
  {
    id: 'inputs',
    title: 'Inputs (Text/Search/Password)',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Inputs need visible labels, nearby error text, and explicit password reveal behavior where relevant.',
  },
  {
    id: 'selects-combobox',
    title: 'Selects / Combobox',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Static selects and searchable selection need governed labeling, loading, empty, and mobile ergonomics.',
  },
  {
    id: 'checkboxes-radios',
    title: 'Checkboxes / Radios',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Checkbox, radio, and switch semantics must remain distinct and predictable.',
  },
  {
    id: 'product-cards',
    title: 'Product Cards',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Structured product cards keep fixed slots for media, metadata, status, and the primary action.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ProductCard',
  },
  {
    id: 'public-product-cards',
    title: 'Public Product Cards',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Media-first public cards must retain price, availability, helper text, and one clear mobile action.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicProductCard',
  },
  {
    id: 'media-card',
    title: 'Media Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Compatibility media card for image-first card surfaces that do not need the full public product contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MediaCard',
  },
  {
    id: 'accent-panels',
    title: 'Accent Panels',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Controls & Inputs',
    summary: 'Accent surfaces must stay readable across color schemes without raw background hacks.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'AccentPanel',
  },
  {
    id: 'metric-cards',
    title: 'Metric Cards',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    summary: 'Metric and progress cards expose value hierarchy, trend semantics, and mobile-safe prioritization. GdsMeter renders a static score with real role="meter" semantics, distinct from a progress bar.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MetricCard / ProgressCard / GdsMeter',
  },
  {
    id: 'data-toolbars',
    title: 'Data Toolbars',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Search, filter, sort, reset, and create affordances must stay in a predictable operational order.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ListingProvider / useListingState / DataToolbar / ActiveFilterChips / ResultSummary / SortMenu / BulkActionsBar',
  },
  {
    id: 'state-blocks',
    title: 'State Blocks',
    docSection: 'Core Component Contracts',
    family: 'feedback',
    section: 'State & Recovery Components',
    summary: 'Loading, empty, error, permission, disabled, and success states now include shared presentation modes for centered/fill bounded surfaces.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'StateBlock / AsyncSurface / MissingDataPrompt',
  },
  {
    id: 'surface-presentation',
    title: 'Surface Presentation',
    docSection: 'Core Component Contracts',
    family: 'feedback',
    section: 'State & Recovery Components',
    summary: 'Shared inline, centered, and fill presentation contract used by state and panel surfaces.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'resolveSurfacePresentationStyles',
  },
  {
    id: 'action-bar',
    title: 'Action Bar',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Priority-driven CTA orchestration belongs to the semantic ActionBar contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ActionBar',
  },
  {
    id: 'listing-card',
    title: 'Listing Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Unified discovery card for events, venues, communities, and similar public objects.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ListingCard',
  },
  {
    id: 'share-button-group',
    title: 'Share Button Group',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Sharing should use governed copy/native/channel actions instead of product-local wrappers.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ShareButtonGroup',
  },
  {
    id: 'public-food-card',
    title: 'Public Food Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Food/menu cards need governed freshness, pickup, scarcity, and bundle semantics.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicFoodCard',
  },
  {
    id: 'food-menu-section',
    title: 'Food Menu Section',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Grouped weekly menus and category-based food composition build on the canonical food-card contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FoodMenuSection',
  },
  {
    id: 'map-panel',
    title: 'Map Panel',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Map System',
    summary: 'Embeds and third-party maps must live inside sanctioned panel chrome with governed states.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MapPanel',
  },
  {
    id: 'detail-profile-shell',
    title: 'Detail Profile Shell',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    summary: 'Canonical page and drawer detail composition with hero, sections, actions, and related content.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DetailProfileShell',
  },
  {
    id: 'public-flow-shell',
    title: 'Public Flow Shell',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Staged consent, review, share, and recovery experiences should use one public-flow shell contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicFlowShell',
  },
  {
    id: 'playback-surface',
    title: 'Playback Surface',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Timed-media and kiosk presentation needs governed playback framing and degraded/error states.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PlaybackSurface',
  },
  {
    id: 'public-shells',
    title: 'Public Shells',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Public marketing, docs, and discovery surfaces need one branded shell contract with mobile nav behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicShell',
  },
  {
    id: 'public-nav',
    title: 'Public Nav',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Primary public navigation uses explicit nav items, active state, and semantic aria-current handling.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicNav',
  },
  {
    id: 'auth-shells',
    title: 'Auth Shells',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Auth entry surfaces must own title, helper/error placement, and canonical social-auth positioning.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'AuthShell',
  },
  {
    id: 'social-auth-buttons',
    title: 'Social Auth Buttons',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Provider-button clusters need governed wording, spacing, loading, and provider-brand treatment.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'SocialAuthButtons',
  },
  {
    id: 'provider-identity-buttons',
    title: 'Provider Identity Buttons',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Canonical provider-brand button and grouped provider-lane components for identity surfaces.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ProviderIdentityButtonGroup',
  },
  {
    id: 'article-shells',
    title: 'Article Shells',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Docs, legal, and editorial reading surfaces need governed width, meta, and side-rail behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ArticleShell',
  },
  {
    id: 'docs-page-shell',
    title: 'Docs Page Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Docs surfaces may add breadcrumbs, next-step links, and code-treatment slots without redefining readability.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DocsPageShell, GdsBreadcrumbs',
  },
  {
    id: 'docs-shell',
    title: 'Docs Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Canonical docs/reference shell for full-width public documentation with governed sidebar and header contracts.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DocsShell',
  },
  {
    id: 'reference-section',
    title: 'Reference Section',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Canonical section framing for official docs/reference pages with governed title, summary, and action rhythm.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ReferenceSection',
  },
  {
    id: 'reference-link-grid',
    title: 'Reference Link Grid',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Canonical docs/reference grid for install, governance, and proof navigation without local card wrappers.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ReferenceLinkGrid',
  },
  {
    id: 'reference-locale-notice',
    title: 'Reference Locale Notice',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Canonical disclosure for partial locale coverage so public language support claims remain explicit and honest.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ReferenceLocaleNotice',
  },
  {
    id: 'reference-theme-explorer',
    title: 'Reference Theme Explorer',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Official interactive explorer for shipped theme lanes, color-scheme preview, and bounded brand-theme controls.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ReferenceThemeExplorer',
  },
  {
    id: 'pin-system',
    title: 'Pin System',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Map System',
    summary: 'Pin anatomy, the solved centre and icon-scale bound surfaced from source, all three composition modes, and a live accent-by-shade contrast matrix.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsPinSystemReference',
  },
  {
    id: 'gds-map',
    title: 'Map Surface',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Map System',
    summary: 'Governed map surface on Leaflet with OpenStreetMap raster tiles, an inseparable ODbL credit, and a labelled announced region.',
    importPath: '@sovereignsquad/gds-core/map',
    sourceComponent: 'GdsMap, GdsMapBasemapWash, GdsMapFilterRail, GdsMapPinPreviewCard',
  },
  {
    id: 'accent-contrast-matrix',
    title: 'Accent Contrast Matrix',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Live accent contrast matrix showing every accent, shade and mode against its measured ratio and required threshold.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsAccentContrastMatrix',
  },
  {
    id: 'design-rule-profile-panel',
    title: 'Design Rule Profile Panel',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Live declared-vs-measured color-proportion donuts plus type-scale and color-harmony badges for the selected theme preset.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsDesignRuleProfilePanel',
  },
  {
    id: 'reference-site-shell',
    title: 'Reference Site Shell',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Canonical reference-site shell for public route grouping and website-level docs/proof structure framing.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'ReferenceSiteShell',
  },
  {
    id: 'editorial-hero',
    title: 'Editorial Hero',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Split text/media public hero sections need one deterministic collapse and CTA hierarchy contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'EditorialHero',
  },
  {
    id: 'feature-band',
    title: 'Feature Band',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Trust, service, and value strips must use a shared multi-column public band contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FeatureBand',
  },
  {
    id: 'browse-surface',
    title: 'Browse Surface',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Catalog/discovery pages use one governed result header, toolbar, filter, and scope rhythm.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'BrowseSurface',
  },
  {
    id: 'editorial-cards',
    title: 'Editorial Cards',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Guide, promo, collection, and discovery cards must share one canonical media/title/meta/CTA contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'EditorialCard',
  },
  {
    id: 'generated-imagery',
    title: 'Generated Imagery',
    docSection: 'Core Component Contracts',
    family: 'systems',
    section: 'Generated Imagery',
    summary: 'Card thumbnails and hero backdrops composed as deterministic, zero-network SVG+HTML from a listing\'s own category data — theme-managed by default (epic 503), so any consumer gets on-brand generated art with no image hosting.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsGeneratedThumbnail / GdsGeneratedHero / GdsGeneratedAvatar / GdsGeneratedMark',
  },
  {
    id: 'consumer-sections',
    title: 'Consumer Sections',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    summary: 'Consumer account and member-dashboard clusters use a shared section shell with governed action placement.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ConsumerSection',
  },
  {
    id: 'consumer-dashboard-grid',
    title: 'Consumer Dashboard Grid',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    summary: 'Metric, progress, and account-summary cards should sit inside a shared responsive dashboard grid.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ConsumerDashboardGrid',
  },
  {
    id: 'media-fields',
    title: 'Media Fields',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Media editing should unify upload, URL entry, preview, status, reset/remove, and policy messaging.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MediaField',
  },
  {
    id: 'content-operations-editor',
    title: 'Content Operations Editor',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Admin settings and content editors need one scaffold for grouped editing, preview rails, and save bars.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'ContentOpsEditor / ContentOpsSection / ContentOpsActionBar',
  },
  {
    id: 'admin-app-shell',
    title: 'Admin App Shell',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Admin compatibility shell built on the canonical DiscoveryShell contract.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'AppShell',
  },
  {
    id: 'editor-scaffold',
    title: 'Editor Scaffold',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Canonical editor scaffold for form, preview, settings, and sticky footer composition.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'EditorScaffold',
  },
  {
    id: 'kanban-board',
    title: 'Kanban Board',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Governed responsive kanban board: portrait mobile stacks columns vertically, landscape/tablet/desktop render multi-column with horizontal scroll. Cards always offer a keyboard-accessible move menu, plus an opt-in pointer/touch/keyboard drag handle (enableDrag) built on accessible sensors rather than native drag-and-drop. Columns support server-pagination counts (totalCount), a per-column footer for load-more/pagination (renderColumnFooter), and controlled collapse/expand (collapsible + collapsedColumnIds).',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'KanbanBoard',
  },
  {
    id: 'form-section',
    title: 'Form Section',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Admin form grouping primitive with title, description, body, and divider rhythm.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'FormSection',
  },
  {
    id: 'workspace-header',
    title: 'Workspace Header',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Editing & Content Ops',
    summary: 'Admin workspace context header with breadcrumbs, description, and action placement.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'WorkspaceHeader',
  },
  {
    id: 'section-panels',
    title: 'Section Panels',
    docSection: 'Core Component Contracts',
    family: 'operations',
    section: 'Dashboard & Panel Surfaces',
    summary: 'Operational panels and detail sections now expose shared panel-body presentation controls (`inline`, `centered`, `fill`) so local wrappers are unnecessary.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'SectionPanel',
  },
  {
    id: 'public-brand-footer',
    title: 'Public Brand Footer',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Narrative and media-driven public footers need a shared layout contract instead of repo-local footer systems.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicBrandFooter',
  },
  {
    id: 'public-site-footer',
    title: 'Public Site Footer',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Simple public footer primitive for lightweight site meta and legal copy.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PublicSiteFooter',
  },
  {
    id: 'filter-drawer',
    title: 'Filter Drawer',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'State & Recovery Components',
    summary: 'Mobile and operational filters must use a shared drawer or bottom-sheet contract with clear apply/reset behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FilterDrawer',
  },
  {
    id: 'docs-code-blocks',
    title: 'Docs Code Blocks',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Shells & Docs',
    summary: 'Install and reference code blocks need a shared wrapper with accessible copy affordances.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'DocsCodeBlock',
  },
  {
    id: 'cta-button-groups',
    title: 'CTA Button Groups',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Editorial & Brand Storytelling',
    summary: 'Public CTA groups must preserve one obvious primary action and stack safely on smaller screens.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'CtaButtonGroup',
  },
  {
    id: 'upload-surfaces',
    title: 'Upload Surfaces',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Upload and drop surfaces need explicit drag state, error, replace, remove, and a11y labeling behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'UploadDropzone',
  },
  {
    id: 'access-summaries',
    title: 'Access Summaries',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Role, scope, blocked, and ownership cues must remain explicit and not rely on color only.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'AccessSummary',
  },
  {
    id: 'access-recovery-panels',
    title: 'Access Recovery Panels',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'State & Recovery Components',
    summary: 'Protected-content and expired-session failures need one canonical recovery surface with clear next actions.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'AccessRecoveryPanel',
  },
  {
    id: 'access-gates',
    title: 'Access Gates',
    docSection: 'Core Component Contracts',
    family: 'access',
    section: 'Auth, Share, & Access',
    summary: 'Paywalls and login gates must expose a public teaser while never rendering protected content until access is unlocked.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsAccessGate / resolveGdsAccessState',
  },
  {
    id: 'placeholder-panels',
    title: 'Placeholder Panels',
    docSection: 'Core Component Contracts',
    family: 'feedback',
    section: 'State & Recovery Components',
    summary: 'Placeholder and coming-soon surfaces must stay honest, visibly non-live, and free of fabricated data.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PlaceholderPanel',
  },
  {
    id: 'simple-data-tables',
    title: 'Simple Data Tables',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Public and product summary tables need governed loading, empty, error, and threshold-safe states.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'SimpleDataTable',
  },
  {
    id: 'admin-data-table',
    title: 'Admin Data Table',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Admin table primitive for operational registries and structured internal records.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'AdvancedDataTable / DataTable',
  },
  {
    id: 'responsive-data-view',
    title: 'Responsive Data View',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Canonical responsive admin data surface that switches table and card strategies intentionally.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'ResponsiveDataView',
  },
  {
    id: 'stats-strip',
    title: 'Stats Strip',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Admin KPI strip for compact repeated operational metrics.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'StatsStrip',
  },
  {
    id: 'info-card',
    title: 'Info Card',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Admin information card for highlighted operational values and supporting detail.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'InfoCard',
  },
  {
    id: 'semantic-nav-link',
    title: 'Semantic Nav Link',
    docSection: 'Core Component Contracts',
    family: 'components',
    section: 'Shell & Navigation',
    summary: 'Admin navigation link that resolves label and icon through the shared semantic vocabulary.',
    importPath: '@sovereignsquad/gds-admin',
    sourceComponent: 'SemanticNavLink',
  },
  {
    id: 'empty-state',
    title: 'Empty State',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'State & Recovery Components',
    summary: 'Compatibility empty-state primitive represented alongside the richer StateBlock contract.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'EmptyState',
  },
  {
    id: 'stats-sections',
    title: 'Stats Sections',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Lightweight reporting sections need explicit loading, threshold, error, and live states.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'StatsSection',
  },
  {
    id: 'reporting-contracts',
    title: 'Reporting Contracts',
    docSection: 'Core Component Contracts',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Reporting-heavy workflows use governed period controls, evidence panels, chart-token wrappers, and fallback tables.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ReportingSection / PeriodSelector / EvidencePanel / ChartTokenPanel / GdsChart / GdsAreaChart / GdsSparkline / GdsLongitudinalChart / GdsBenchmarkBarChart / GdsRadarChart / GdsMaturityRadarChart / GdsGaugeChart',
  },
  {
    id: 'alerts',
    title: 'Alerts',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Overlays & Feedback',
    summary: 'Alerts must explain the current state and the next action instead of acting as decorative chrome.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'InlineAlert / BannerNotice / GdsTelemetryProvider',
  },
  {
    id: 'loaders-skeletons',
    title: 'Loaders & Skeletons',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Overlays & Feedback',
    summary: 'Skeletons belong to known layouts, while loaders belong to actions and longer operations need explicit text status.',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Overlays & Feedback',
    summary: 'Notifications use the governed queue for severity, retry, announcement-only updates, persistence, and metadata-only audit events.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsNotificationProvider / GdsNotificationCenter / NotificationCenter / InlineAlert / BannerNotice',
  },
  {
    id: 'motion-system',
    title: 'Motion Tokens',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Motion Tokens',
    summary: 'Six governed durations, five easings, seven named presets and the reaction axis — every value surfaced live from the exports consumers import, with reduced motion honoured by the tokens themselves. For interactive click/action feedback (icon, color, and message on click), see Semantic Actions under Workflow Guidance.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsMotionSystemReference',
  },
  {
    id: 'shape-elevation',
    title: 'Shape & Elevation Tokens',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Shape & Elevation',
    summary: 'Seven radius steps and five elevation steps, each with named semantic roles (card, button, pin, modal, tooltip…) so component source asks for a role, never a raw step — every value surfaced live from resolveGdsShapeTokens() and resolveGdsElevationTokens(), the same resolvers a theme’s own token pipeline calls.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsShapeElevationSystemReference',
  },
  {
    id: 'density-spacing',
    title: 'Density & Spacing Tokens',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Density & Spacing',
    summary: 'Ten spacing steps and five control-height sizes, scaled together by one comfortable/compact/spacious density factor — control heights hold the 44px accessibility floor unless a size carries a recorded exception, even under a tightened density. Surfaced live from resolveGdsDensityTokens().',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsDensitySpacingSystemReference',
  },
  {
    id: 'icon-system',
    title: 'Icon System',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Icons',
    summary: 'The whole governed icon dictionary, its semantic categories, colour tones, and the decorative-vs-informative accessibility contract — every icon rendered through GdsIcon rather than a direct Tabler import, walked live from getGdsIconKeys()/getGdsIconMetadata() (counts shown below are computed at render time, not typed here).',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsIconSystemReference',
  },
  {
    id: 'typography',
    title: 'Typography Tokens',
    docSection: 'Core Component Contracts',
    family: 'foundations',
    section: 'Typography',
    summary: 'A modular text-size scale, an ascending weight scale validated at construction, and the display/body/mono font-lane roles a theme assigns — every specimen rendered at its own resolved size, live from resolveGdsTypographyTokens().',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'GdsTypographySystemReference',
  },
  {
    id: 'badges',
    title: 'Badges',
    docSection: 'Feedback & Messaging',
    family: 'systems',
    section: 'Badges & Indicators',
    summary: 'Badges are compact state cues and must not rely on color only. The shape vocabulary renders Tabler-geometry silhouettes for composed badge marks.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'StatusBadge / CountBadge / LabelTag / GdsBadgeShapeCircle / GdsBadgeShapeSquircle / GdsBadgeShapeHexagon / GdsBadgeShapeShield / GdsBadgeShapeRosette / GdsBadgeShapePin / GdsBadge / GdsBadgeStack / GdsBadgeStackLayer / GdsCountBadge / GdsRemovableTag / GdsIconBadge / GdsVibeThemeScope / GdsMapPinBadge / GdsIconStyleContext (SportsEmojiModeDemo scopes the badge glyph mode directly; useGdsBadgeIconStyle is exercised internally by GdsBadge/GdsMapPinBadge whenever that demo renders) / GdsSavedIndicator / GdsRatingDisplay',
  },
  {
    id: 'modals',
    title: 'Modals',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Overlays & Feedback',
    summary: 'Modals support focused edits and confirmations with trapped focus and no stacking.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ConfirmDialog / OverlayManagerProvider / GdsDialog',
  },
  {
    id: 'drawers',
    title: 'Drawers',
    docSection: 'Feedback & Messaging',
    family: 'feedback',
    section: 'Overlays & Feedback',
    summary: 'Drawers support filters and secondary panels with explicit mobile and desktop sizing behavior.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FilterDrawer / CommandRegistryProvider / GdsSidePanel',
  },
  {
    id: 'small-screen-priority',
    title: 'Small-Screen Priority',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'feedback',
    section: 'Responsive Guidance',
    summary: 'On small screens the system prioritizes next actions, urgent exceptions, recent work, then analytics.',
  },
  {
    id: 'table-responsive-strategies',
    title: 'Table Responsive Strategies',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'data',
    section: 'Responsive Guidance',
    summary: 'Desktop tables must adapt through scroll, cards, priority columns, or stacked rows rather than naive shrinking.',
  },
  {
    id: 'mobile-action-density',
    title: 'Mobile Action Density',
    docSection: 'Responsive Behavior & Touch Ergonomics',
    family: 'feedback',
    section: 'Responsive Guidance',
    summary: 'Cards should keep one visible primary action on mobile and avoid risky icon-only adjacency.',
  },
  {
    id: 'searchable-selection',
    title: 'Searchable Selection',
    docSection: 'Required Reusable Pattern Families',
    family: 'data',
    section: 'Search & Data Views',
    summary: 'Searchable selection follows the documented Mantine recipe path until a dedicated GDS export is promoted.',
  },
  {
    id: 'vocabulary-extension-lane',
    title: 'Semantic Vocabulary Extension Lane',
    docSection: 'Semantic Vocabulary Extension Lane',
    family: 'operations',
    section: 'Workflow Guidance',
    summary: 'Products may extend semantic action vocabulary through governed namespaced packs rather than raw labels.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'createGdsVocabularyPack',
  },
  {
    id: 'partner-discovery-system',
    title: 'Partner Discovery System',
    docSection: 'Partner Discovery Compatibility',
    family: 'public',
    section: 'Public Product Surfaces',
    summary: 'Issue-backed partner-compatible discovery system covering theme, shell, filters, map/list, detail, newsletter, content, observability, validation, and non-copy boundaries.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'PartnerDiscoveryShell / PartnerDiscoveryFilters / PartnerMapListShell / PartnerPlaceDetailTemplate / PartnerNewsletterCapture / PartnerListIndex / PartnerFaqList / PartnerSubmissionEntry',
  },
  {
    id: 'bottom-tab-navigation',
    title: 'Bottom Tab Navigation',
    docSection: 'Application Shell & Navigation',
    family: 'public',
    section: 'Shell & Navigation Guidance',
    summary: 'Mobile-first persistent bottom tab bar driven by nav items, with safe-area insets, an active token, and an optional raised center action.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'BottomTabBar, BOTTOM_TAB_MAX_ITEMS, BOTTOM_TAB_HEIGHT, GdsViewportFrame',
  },
  {
    id: 'searchable-select',
    title: 'Searchable Select',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Forms & Inputs',
    summary: 'Searchable single-select / combobox with async options, grouping, clearable value, and full WAI-ARIA keyboard accessibility.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'SearchableSelect',
  },
  {
    id: 'fit-score-chip',
    title: 'Fit Score Chip',
    docSection: 'Core Component Contracts',
    family: 'systems',
    section: 'Badges & Indicators',
    summary: 'Compact match-quality pill on a sage to terracotta band scale with an accessible tooltip, distinct from status badges.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'FitScoreChip',
  },
  {
    id: 'conversation-surface',
    title: 'Conversation Surface',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Product Surfaces',
    summary: 'Assistant chat surface: an auto-scrolling live-region thread, role-styled bubbles with embedded result cards, streaming indicator, and an Enter-to-send input.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'ChatThread, ChatMessage, ChatInput, StreamingIndicator',
  },
  {
    id: 'meaning-badge',
    title: 'Meaning Badge',
    docSection: 'Core Component Contracts',
    family: 'systems',
    section: 'Badges & Indicators',
    summary: 'Editorial brand-meaning labels (attention, validation, info, urgency) kept separate from system status badges.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MeaningBadge',
  },
  {
    id: 'media-with-fallback',
    title: 'Media With Fallback',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Discovery & Listing',
    summary: 'Image primitive with a branded fallback and reserved aspect-ratio box so a failed image never collapses a card or shifts layout.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'MediaWithFallback',
  },
  {
    id: 'number-stepper',
    title: 'Number Stepper',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Forms & Inputs',
    summary: 'Bounded accessible quantity stepper with clamp/snap, keyboard support, and spinbutton semantics.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'NumberStepper',
  },
  {
    id: 'ai-search-card',
    title: 'AI Search Card',
    docSection: 'Core Component Contracts',
    family: 'public',
    section: 'Public Product Surfaces',
    summary: 'Governed AI search entry surface composing a search input, BETA meaning badge, and prompt chips that route a query into the assistant.',
    importPath: '@sovereignsquad/gds-core',
    sourceComponent: 'AISearchCard',
  },
];

const provenIds = new Set(provenPatternIds);

export const patternRegistry: PatternRegistryEntry[] = rawPatternRegistry.map((entry) => ({
  ...entry,
  route: `/patterns/${entry.family}`,
  anchor: entry.id,
  // provenPatternIds is generated from pattern-pages.tsx's renderEntryDemo() cases.
  coverageStatus: provenIds.has(entry.id) ? 'live-proof' : 'static-reference',
}));

export const documentedPatternIds = patternRegistry.map((entry) => entry.id);

export function getFamilyEntries(family: PatternFamily) {
  return patternRegistry.filter((entry) => entry.family === family);
}
